import type { Entity } from "./types";

export const desk: Entity[] = [
  // ── Events ─────────────────────────────────────────────────
  {
    id: "xbiz-2026",
    kind: "events",
    name: "XBIZ 2026",
    subtitle: "Trade show · Hollywood",
    summary:
      "North American flagship adult-industry trade show. Studios, platforms, talent, and buyers. 12–15 January 2026, Hollywood.",
    body: "XBIZ is the principal West Coast trade gathering: meetings, product, and the XBIZ Awards. The 2026 edition ran 12–15 January in Hollywood. fleshsesh indexes it as a public calendar record.",
    tags: ["trade-show", "awards", "hollywood", "public"],
    region: "Hollywood, California",
    status: "Past",
    venue: "Hollywood, California",
    dateStart: "2026-01-12",
    dateEnd: "2026-01-15",
    facts: [
      { label: "When", value: "12–15 January 2026" },
      { label: "Where", value: "Hollywood, California" },
      { label: "Type", value: "Trade show & awards" },
    ],
    related: [
      { kind: "companies", id: "copperline-pr" },
      { kind: "companies", id: "fsc" },
      { kind: "events", id: "avn-expo-2026" },
    ],
    socials: [{ platform: "Site", handle: "xbiz.com" }],
    source: "public",
  },
  {
    id: "avn-expo-2026",
    kind: "events",
    name: "AVN Expo 2026",
    subtitle: "Expo · Las Vegas",
    summary:
      "Largest U.S. adult expo. Floor, seminars, and the AVN Awards. 21–24 January 2026, Virgin Hotels Las Vegas.",
    body: "The AVN Expo (Adult Entertainment Expo) concentrates studios, pleasure brands, talent, and press in Las Vegas each January. The 2026 show ran 21–24 January at Virgin Hotels Las Vegas. Awards night sits inside the same week.",
    tags: ["expo", "awards", "las-vegas", "public"],
    region: "Las Vegas",
    status: "Past",
    venue: "Virgin Hotels Las Vegas",
    dateStart: "2026-01-21",
    dateEnd: "2026-01-24",
    facts: [
      { label: "When", value: "21–24 January 2026" },
      { label: "Where", value: "Virgin Hotels Las Vegas" },
      { label: "Type", value: "Expo & awards" },
    ],
    related: [
      { kind: "events", id: "palisade-honors-2026" },
      { kind: "companies", id: "eastbound" },
      { kind: "companies", id: "fsc" },
    ],
    socials: [{ platform: "Site", handle: "avn.com" }],
    source: "public",
  },
  {
    id: "venus-berlin-2026",
    kind: "events",
    name: "Venus Berlin 2026",
    subtitle: "Trade fair · Berlin",
    summary:
      "Europe's largest adult products and multimedia fair. 22–25 October 2026, Messe Berlin.",
    body: "Venus Berlin, held since the mid-1990s at the Messegelände, is the European trade and consumer fair for adult products, platforms, and performance. The 2026 edition is 22–25 October. Afterlight Media and Sabine Köhler's book typically work the floor.",
    tags: ["trade-fair", "berlin", "europe", "public", "upcoming"],
    region: "Berlin",
    status: "Upcoming",
    venue: "Messe Berlin",
    dateStart: "2026-10-22",
    dateEnd: "2026-10-25",
    facts: [
      { label: "When", value: "22–25 October 2026" },
      { label: "Where", value: "Messe Berlin" },
      { label: "Type", value: "Trade fair" },
    ],
    related: [
      { kind: "companies", id: "afterlight-media" },
      { kind: "agents", id: "sabine-kohler" },
      { kind: "productions", id: "corridor" },
    ],
    socials: [{ platform: "Site", handle: "venus-berlin.com" }],
    source: "public",
  },
  {
    id: "palisade-honors-2026",
    kind: "events",
    name: "Palisade Honors 2026",
    subtitle: "Awards · Las Vegas",
    summary:
      "Palisade Institute's annual craft ballot and ceremony, held during Las Vegas expo week.",
    tags: ["awards", "las-vegas"],
    region: "Las Vegas",
    status: "Past",
    venue: "Las Vegas",
    dateStart: "2026-01-23",
    facts: [
      { label: "When", value: "23 January 2026" },
      { label: "Body", value: "Palisade Institute" },
    ],
    related: [
      { kind: "companies", id: "palisade-institute" },
      { kind: "events", id: "avn-expo-2026" },
      { kind: "productions", id: "glass-harbor" },
    ],
    source: "index",
  },
  {
    id: "nightjar-forum-2026",
    kind: "events",
    name: "Nightjar Forum 2026",
    subtitle: "Creator & director forum",
    summary:
      "Small Los Angeles forum for performer-directors, stills, and independent slates. 12–14 November 2026.",
    tags: ["forum", "directors", "los-angeles", "upcoming"],
    region: "Los Angeles",
    status: "Upcoming",
    venue: "Los Angeles",
    dateStart: "2026-11-12",
    dateEnd: "2026-11-14",
    facts: [
      { label: "When", value: "12–14 November 2026" },
      { label: "Host", value: "Nightjar Films" },
    ],
    related: [
      { kind: "companies", id: "nightjar-films" },
      { kind: "performers", id: "wren-solis" },
      { kind: "performers", id: "isla-vane" },
    ],
    source: "index",
  },
  {
    id: "counsel-day-2026",
    kind: "events",
    name: "Counsel Day 2026",
    subtitle: "Legal briefing",
    summary:
      "Annual CLE-style briefing from Counsel Group: 2257, state age-verification maps, TAKE IT DOWN, and card-network rules. 18 September 2026, Los Angeles.",
    tags: ["legal", "compliance", "los-angeles", "upcoming"],
    region: "Los Angeles",
    status: "Upcoming",
    venue: "Los Angeles",
    dateStart: "2026-09-18",
    facts: [
      { label: "When", value: "18 September 2026" },
      { label: "Host", value: "Counsel Group" },
    ],
    related: [
      { kind: "companies", id: "counsel-group" },
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "take-it-down" },
      { kind: "performers", id: "nico-bell" },
    ],
    source: "index",
  },
  {
    id: "ledger-week-2026",
    kind: "events",
    name: "Ledger Week 2026",
    subtitle: "Creator convening",
    summary:
      "Direct-to-fan and platform week. Panels on 2257 for solo producers, payments, and notice-and-removal. March 2026, Phoenix.",
    tags: ["creators", "platforms", "phoenix"],
    region: "Phoenix",
    status: "Past",
    venue: "Phoenix, Arizona",
    dateStart: "2026-03-04",
    dateEnd: "2026-03-07",
    facts: [
      { label: "When", value: "4–7 March 2026" },
      { label: "Where", value: "Phoenix" },
    ],
    related: [
      { kind: "performers", id: "noa-pell" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "law", id: "usc-2257" },
    ],
    source: "index",
  },

  // ── Law ────────────────────────────────────────────────────
  {
    id: "usc-2257",
    kind: "law",
    name: "18 U.S.C. § 2257",
    subtitle: "Record-keeping requirements",
    citation: "18 U.S.C. § 2257",
    jurisdiction: "United States (federal)",
    summary:
      "Federal criminal statute requiring producers of actual sexually explicit visual depictions to examine picture identification, keep indexed records, and affix a custodian statement to every copy — including every webpage.",
    body: "Section 2257 is the backbone of adult-industry compliance in the United States. Anyone who produces visual depictions of actual sexually explicit conduct must, before production, examine a government-issued picture identification document for every performer, record the legal name and date of birth, cross-index every alias and stage name, and keep those records available for inspection. A statement naming the Custodian of Records and a physical address must appear on every copy, including every page of a website on which the matter appears.\n\nPrimary producers (the people who actually shoot) and secondary producers (those who duplicate, manage content, or publish) both have duties; platforms such as Vellum typically take a secondary-producer posture while creators remain primary producers of their own work. Failure is a federal felony — up to five years for a first offense.\n\nThis is a summary of public law, not legal advice. Producers should retain qualified counsel and read 28 C.F.R. Part 75 alongside the statute.",
    tags: ["federal", "2257", "records", "criminal", "producers"],
    status: "In force",
    facts: [
      { label: "Citation", value: "18 U.S.C. § 2257" },
      { label: "Enacted posture", value: "Post-1990 depictions" },
      { label: "Penalty", value: "Felony; up to 5 years (first)" },
      { label: "Companion", value: "28 C.F.R. Part 75" },
    ],
    related: [
      { kind: "law", id: "usc-2257a" },
      { kind: "law", id: "cfr-28-75" },
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "companies", id: "counsel-group" },
    ],
    source: "public",
  },
  {
    id: "usc-2257a",
    kind: "law",
    name: "18 U.S.C. § 2257A",
    subtitle: "Simulated depictions",
    citation: "18 U.S.C. § 2257A",
    jurisdiction: "United States (federal)",
    summary:
      "Extends 2257-style record-keeping to simulated sexually explicit conduct and to lascivious exhibition, with a certification exemption for some mainstream producers.",
    body: "Section 2257A covers visual depictions of simulated sexually explicit conduct and certain lascivious exhibition. Producers must keep performer records similar to § 2257 unless they qualify for a certification exemption used mainly by mainstream film and television that already complies with other child-protection regimes.\n\nAdult producers generally should not assume they qualify for that exemption. Counsel Group's desk treats 2257 and 2257A as one program with two statutory hooks.\n\nNot legal advice.",
    tags: ["federal", "2257a", "simulated", "records"],
    status: "In force",
    facts: [
      { label: "Citation", value: "18 U.S.C. § 2257A" },
      { label: "Covers", value: "Simulated conduct; lascivious exhibition" },
    ],
    related: [
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "cfr-28-75" },
    ],
    source: "public",
  },
  {
    id: "cfr-28-75",
    kind: "law",
    name: "28 C.F.R. Part 75",
    subtitle: "Attorney General regulations",
    citation: "28 C.F.R. §§ 75.1–75.9",
    jurisdiction: "United States (federal)",
    summary:
      "The regulations that make 2257 operational: what a record must contain, how it is indexed, where it is kept, how long, and how it is inspected.",
    body: "Part 75 is the operational manual for §§ 2257 and 2257A. It specifies picture-identification copies, alphabetical indexing by legal name with cross-references for aliases and titles, retention (generally seven years from creation or last amendment, and five years after a producer leaves the business — whichever runs longer), and inspection during ordinary business hours.\n\nA 2257 program that tracks the statute but ignores Part 75 is incomplete. Custodians, filenames, and URL indexes live here.\n\nNot legal advice.",
    tags: ["federal", "regulation", "2257", "retention"],
    status: "In force",
    facts: [
      { label: "Citation", value: "28 C.F.R. Part 75" },
      { label: "Retention", value: "7 years / 5 years after exit" },
    ],
    related: [
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "usc-2257a" },
    ],
    source: "public",
  },
  {
    id: "fosta-sesta",
    kind: "law",
    name: "FOSTA-SESTA",
    subtitle: "Platform liability carve-out",
    citation: "Allow States and Victims to Fight Online Sex Trafficking Act, Pub. L. 115–164",
    jurisdiction: "United States (federal)",
    summary:
      "2018 statute that carved sex-trafficking claims out of Section 230 immunity and created federal civil and criminal exposure for platforms that promote or facilitate prostitution.",
    body: "FOSTA-SESTA, signed in 2018, narrowed 47 U.S.C. § 230 so that platforms can be held responsible for certain sex-trafficking and prostitution-related activity. It did not outlaw adult content, but it changed how hosts, classifieds, and social products moderate sexual services and escort advertising.\n\nThe practical effect on the trade has been a chill in advertising channels, more aggressive terms of service, and a migration of independent work onto platforms that can show a compliance story. It sits beside, and is often confused with, 18 U.S.C. § 1591.\n\nNot legal advice.",
    tags: ["federal", "platforms", "section-230", "trafficking"],
    status: "In force",
    facts: [
      { label: "Enacted", value: "2018" },
      { label: "Public law", value: "Pub. L. 115–164" },
      { label: "Hooks", value: "§ 230 carve-out; 18 U.S.C. § 2421A" },
    ],
    related: [
      { kind: "law", id: "section-230" },
      { kind: "law", id: "usc-1591" },
      { kind: "companies", id: "aurelia-network" },
      { kind: "companies", id: "fsc" },
    ],
    source: "public",
  },
  {
    id: "section-230",
    kind: "law",
    name: "47 U.S.C. § 230",
    subtitle: "Platform immunity",
    citation: "47 U.S.C. § 230",
    jurisdiction: "United States (federal)",
    summary:
      "Communications Decency Act provision that generally immunizes interactive computer services from liability for third-party speech, with statutory exceptions including federal criminal law and FOSTA's trafficking carve-out.",
    body: "Section 230 is why user-generated platforms can host speech without being treated as the publisher of every post. Adult platforms rely on it for comments, profiles, and uploaded media — subject to federal criminal law (including 2257's own duties where they apply) and the FOSTA-SESTA exceptions.\n\nIt is not a license to ignore record-keeping, age-verification statutes, or the TAKE IT DOWN Act's notice-and-removal duties, which are separate regimes.\n\nNot legal advice.",
    tags: ["federal", "platforms", "immunity", "cda"],
    status: "In force",
    facts: [
      { label: "Citation", value: "47 U.S.C. § 230" },
      { label: "Enacted", value: "1996" },
    ],
    related: [
      { kind: "law", id: "fosta-sesta" },
      { kind: "law", id: "take-it-down" },
      { kind: "law", id: "dmca-512" },
    ],
    source: "public",
  },
  {
    id: "miller-v-california",
    kind: "law",
    name: "Miller v. California",
    subtitle: "Obscenity test",
    citation: "413 U.S. 15 (1973)",
    jurisdiction: "United States (Supreme Court)",
    summary:
      "The three-part test that decides whether material is legally obscene — and therefore unprotected by the First Amendment.",
    body: "Miller asks whether the average person, applying contemporary community standards, would find that the work, taken as a whole, appeals to the prurient interest; whether it depicts sexual conduct in a patently offensive way as defined by state law; and whether it lacks serious literary, artistic, political, or scientific value.\n\nMost commercially distributed adult material is designed to sit on the protected side of Miller. The test still governs criminal obscenity prosecutions and is the backdrop against which later cases (Ashcroft, Paxton) reason about what states may do to keep material from minors.\n\nNot legal advice.",
    tags: ["case", "obscenity", "first-amendment", "supreme-court"],
    status: "Leading case",
    facts: [
      { label: "Citation", value: "413 U.S. 15 (1973)" },
      { label: "Court", value: "U.S. Supreme Court" },
    ],
    related: [
      { kind: "law", id: "ashcroft-fsc" },
      { kind: "law", id: "fsc-v-paxton" },
    ],
    source: "public",
  },
  {
    id: "ashcroft-fsc",
    kind: "law",
    name: "Ashcroft v. Free Speech Coalition",
    subtitle: "Virtual depictions",
    citation: "535 U.S. 234 (2002)",
    jurisdiction: "United States (Supreme Court)",
    summary:
      "Struck down parts of the CPPA that banned sexually explicit images that appeared to depict minors but were produced without real children — including adult actors and purely virtual images.",
    body: "The Court held that the First Amendment does not permit Congress to ban protected adult speech merely because it might be mistaken for illegal child pornography. The government may prohibit images of actual children; it may not, on that record, prohibit speech that only appears to involve them.\n\nThe decision is why adult producers can depict characters who are written as adults (and are performed by adults), and why later age-verification fights are framed as burdens on adults' access rather than as a ban on the speech itself.\n\nNot legal advice.",
    tags: ["case", "first-amendment", "supreme-court", "cppa"],
    status: "Leading case",
    facts: [
      { label: "Citation", value: "535 U.S. 234 (2002)" },
      { label: "Plaintiff", value: "Free Speech Coalition" },
    ],
    related: [
      { kind: "law", id: "miller-v-california" },
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "companies", id: "fsc" },
    ],
    source: "public",
  },
  {
    id: "fsc-v-paxton",
    kind: "law",
    name: "Free Speech Coalition v. Paxton",
    subtitle: "Age verification upheld",
    citation: "605 U.S. ___ (2025)",
    jurisdiction: "United States (Supreme Court)",
    summary:
      "June 27, 2025. The Court held 6–3 that Texas H.B. 1181's commercial age-verification requirement for sites with a substantial amount of material that is obscene to minors survives intermediate scrutiny.",
    body: "Texas H.B. 1181 requires certain commercial sites that publish sexually explicit material obscene to minors to verify that visitors are 18 or older. The Fifth Circuit had applied rational-basis review. The Supreme Court, in an opinion by Justice Thomas, held that the law only incidentally burdens adults' protected speech, is subject to intermediate scrutiny, and survives that review. Adults, the Court said, have no First Amendment right to access such speech without first submitting proof of age.\n\nJustice Kagan dissented, joined by Justices Sotomayor and Jackson. The decision effectively opened the door to similar statutes nationwide and is the reason many aggregators geo-fence or age-gate whole U.S. states. It sits in tension with older cases that applied strict scrutiny to similar burdens (including a 2004 decision the majority declined to follow).\n\nNot legal advice. Read the opinion; state statutes differ in coverage threshold, acceptable methods, and penalties.",
    tags: ["case", "age-verification", "texas", "supreme-court", "first-amendment"],
    status: "Decided 27 June 2025",
    facts: [
      { label: "Decided", value: "27 June 2025" },
      { label: "Vote", value: "6–3" },
      { label: "Author", value: "Thomas, J." },
      { label: "Docket", value: "23-1122" },
      { label: "Statute", value: "Texas H.B. 1181" },
    ],
    related: [
      { kind: "law", id: "texas-hb-1181" },
      { kind: "law", id: "state-av-laws" },
      { kind: "law", id: "ashcroft-fsc" },
      { kind: "companies", id: "fsc" },
      { kind: "companies", id: "aurelia-network" },
    ],
    source: "public",
  },
  {
    id: "texas-hb-1181",
    kind: "law",
    name: "Texas H.B. 1181",
    subtitle: "Commercial age verification",
    citation: "Tex. Civ. Prac. & Rem. Code ch. 129B",
    jurisdiction: "Texas",
    summary:
      "Requires covered commercial websites that publish a substantial portion of material harmful to minors to use reasonable age-verification methods. Civil penalties and injunctions. Upheld in FSC v. Paxton.",
    body: "H.B. 1181 is the statute the Supreme Court reviewed in 2025. Coverage is keyed to a commercial site's publication of sexually explicit material that is obscene to minors, typically at a one-third threshold. Acceptable methods include government ID and commercial age-verification systems. Knowing violations expose covered entities to injunctions and civil penalties.\n\nAfter Paxton, analog statutes in other states are harder to preliminarily enjoin on First Amendment grounds. Implementation details — which vendors, what data retention, what to do with VPN traffic — remain a compliance practice, not a constitutional given.\n\nNot legal advice.",
    tags: ["texas", "age-verification", "civil", "platforms"],
    status: "In force; upheld 2025",
    facts: [
      { label: "Jurisdiction", value: "Texas" },
      { label: "Enacted", value: "2023" },
      { label: "Review", value: "Upheld, FSC v. Paxton" },
    ],
    related: [
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "state-av-laws" },
    ],
    source: "public",
  },
  {
    id: "state-av-laws",
    kind: "law",
    name: "State age-verification statutes",
    subtitle: "The post-Paxton map",
    jurisdiction: "U.S. states",
    summary:
      "A growing set of state laws requiring commercial adult sites to verify age. After FSC v. Paxton (2025), similar statutes are on firmer constitutional ground. Coverage, methods, and penalties still vary.",
    body: "Louisiana's 2023 Act 440 was an early model; Texas, Utah, Virginia, Mississippi, and others followed with their own coverage thresholds and vendor rules. Some states require a registered-agent or reporting duty; some impose civil liability to individuals; some are criminal.\n\nPaxton did not write a national statute. A site that geo-fences Texas is not thereby compliant in every other state. Counsel Day 2026 is built around this map. Aggregators (Aurelia) and live platforms (Cobalt) have been the first to implement hard gates or withdrawals.\n\nNot legal advice. Check current bill text; this desk does not host a live legislative tracker.",
    tags: ["states", "age-verification", "platforms", "compliance"],
    status: "Patchwork; expanding",
    facts: [
      { label: "Trigger case", value: "FSC v. Paxton (2025)" },
      { label: "Early model", value: "Louisiana Act 440 (2023)" },
    ],
    related: [
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "texas-hb-1181" },
      { kind: "companies", id: "cobalt-interactive" },
      { kind: "events", id: "counsel-day-2026" },
    ],
    source: "public",
  },
  {
    id: "measure-b",
    kind: "law",
    name: "L.A. County Measure B",
    subtitle: "Safer-sex ordinance",
    citation: "Los Angeles County Safer Sex in the Adult Film Industry Act",
    jurisdiction: "Los Angeles County, California",
    summary:
      "2012 voter-approved ordinance requiring condom use in adult films shot in Los Angeles County and a public-health permit for producers.",
    body: "Measure B is a county public-health ordinance, not a federal speech statute. It pushed a substantial share of production out of Los Angeles County in the 2010s. California's statewide Proposition 60 (2016), which would have expanded similar rules, failed.\n\nStudios still shooting in the county treat permitting and on-set protocols as a production cost. Houses in this index list a mix of county and out-of-county stages.\n\nNot legal advice.",
    tags: ["california", "los-angeles", "public-health", "production"],
    status: "In force (county)",
    facts: [
      { label: "Approved", value: "2012" },
      { label: "Jurisdiction", value: "Los Angeles County" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "northstar-pictures" },
    ],
    source: "public",
  },
  {
    id: "ab5-classification",
    kind: "law",
    name: "California A.B. 5",
    subtitle: "Worker classification",
    citation: "Cal. Lab. Code § 2775 et seq. (A.B. 5, 2019)",
    jurisdiction: "California",
    summary:
      "Codifies the ABC test for employee versus independent contractor. Adult performers, crew, and some creators working in California have to be classified under it unless an exemption applies.",
    body: "A.B. 5 and the Dynamex ABC test make it harder to treat on-set labor as a roster of independent contractors. Subsequent legislation carved exemptions for some professions; adult performance is not a clean statutory carve-out, so California producers often mix payroll companies, loan-outs, and W-2 days.\n\nDirect-to-fan creators shooting alone in California face a different question than a Helix call sheet. Misclassification risk is a labor issue, not a 2257 issue — they stack.\n\nNot legal advice.",
    tags: ["california", "labor", "classification", "ab5"],
    status: "In force",
    facts: [
      { label: "Enacted", value: "2019" },
      { label: "Test", value: "ABC / Dynamex" },
    ],
    related: [
      { kind: "law", id: "work-for-hire" },
      { kind: "companies", id: "helix-house" },
    ],
    source: "public",
  },
  {
    id: "uk-online-safety",
    kind: "law",
    name: "UK Online Safety Act 2023",
    subtitle: "Age assurance, duties of care",
    citation: "Online Safety Act 2023 (UK)",
    jurisdiction: "United Kingdom",
    summary:
      "Imposes duties of care on user-to-user and search services, including highly effective age assurance for pornography. Ofcom is the regulator.",
    body: "The Online Safety Act requires services that publish or user-generate pornography to prevent children from encountering it, using highly effective age assurance. Ofcom's codes and the Part 5 duties on pornographic content have driven UK age-gating, withdrawals, and VPN workarounds similar to the U.S. state map — on a national scale.\n\nAfterlight's UK-facing storefront and Tamsin Rowe's producer notes treat OSA as a product requirement, not a terms footnote.\n\nNot legal advice. Ofcom guidance changes.",
    tags: ["united-kingdom", "ofcom", "age-assurance", "platforms"],
    status: "In force",
    facts: [
      { label: "Enacted", value: "2023" },
      { label: "Regulator", value: "Ofcom" },
    ],
    related: [
      { kind: "law", id: "eu-dsa" },
      { kind: "performers", id: "tamsin-rowe" },
      { kind: "companies", id: "afterlight-media" },
    ],
    source: "public",
  },
  {
    id: "eu-dsa",
    kind: "law",
    name: "EU Digital Services Act",
    subtitle: "Platform due diligence",
    citation: "Regulation (EU) 2022/2065",
    jurisdiction: "European Union",
    summary:
      "EU-wide rules for intermediary services: notice-and-action, transparency, risk assessment for very large platforms, and protection of minors — including age-assurance expectations for adult content.",
    body: "The DSA is a regulation, directly applicable. Hosting services must provide notice-and-action for illegal content; very large platforms carry additional risk-assessment and audit duties. Combined with member-state criminal law and the forthcoming / adjacent age-assurance standards, it is the European compliance ceiling for Aurelia-style aggregators and Afterlight's own storefront.\n\nIllegal content under the DSA is defined by other law (including CSAM, which has no place in this industry and is not indexed here).\n\nNot legal advice.",
    tags: ["european-union", "platforms", "dsa", "age-assurance"],
    status: "In force",
    facts: [
      { label: "Citation", value: "Reg. (EU) 2022/2065" },
      { label: "Applies", value: "EU intermediary services" },
    ],
    related: [
      { kind: "law", id: "uk-online-safety" },
      { kind: "companies", id: "afterlight-media" },
      { kind: "companies", id: "aurelia-network" },
    ],
    source: "public",
  },
  {
    id: "take-it-down",
    kind: "law",
    name: "TAKE IT DOWN Act",
    subtitle: "NCII and deepfakes",
    citation: "Pub. L. 119–12 (2025)",
    jurisdiction: "United States (federal)",
    summary:
      "Criminalizes knowing publication (or threats) of nonconsensual intimate images, including AI digital forgeries, and requires covered platforms to remove reported depictions and identical copies within 48 hours. FTC enforcement of the platform duty began 19 May 2026.",
    body: "The Tools to Address Known Exploitation by Immobilizing Technological Deepfakes on Websites and Networks Act was signed 19 May 2025. It has two engines: a criminal prohibition on knowingly publishing, or threatening to publish, nonconsensual intimate visual depictions of an identifiable person — authentic or AI-generated — and a platform notice-and-removal duty.\n\nCovered platforms must publish a process, then remove the identified depiction and make reasonable efforts to strip known identical copies as soon as possible, not later than 48 hours after a valid request. The FTC treats failures as rule violations; its portal opened when the platform provisions took effect on 19 May 2026.\n\nThis is distinct from 2257 (which is about age and identity of performers who consented to production) and from FOSTA (trafficking). Talent managers such as Nina Braswell now treat TAKE IT DOWN notices as a standard representation task.\n\nNot legal advice.",
    tags: ["federal", "ncii", "deepfakes", "platforms", "ftc"],
    status: "In force; FTC duty live 19 May 2026",
    facts: [
      { label: "Public law", value: "Pub. L. 119–12" },
      { label: "Signed", value: "19 May 2025" },
      { label: "Platform duty", value: "48 hours; FTC from 19 May 2026" },
    ],
    related: [
      { kind: "law", id: "section-230" },
      { kind: "law", id: "dmca-512" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "agents", id: "nina-braswell" },
    ],
    source: "public",
  },
  {
    id: "card-networks",
    kind: "law",
    name: "Card-network integrity rules",
    subtitle: "Mastercard AN 5196 · Visa VIRP",
    jurisdiction: "Payment networks (global)",
    summary:
      "Private-network rules, not statutes. In 2025–2026 they became a de facto production standard: documented performer consent, 2257-quality records, and brand-protection reviews as a condition of taking cards.",
    body: "Mastercard's adult-content announcement (AN 5196) and Visa's Integrity Risk Program sit outside the U.S. Code but decide whether a studio or creator can get paid. Networks have asked acquirers for evidence of age, consent, and — in practice — signed releases that federal 2257 never required.\n\nA producer can be 2257-clean and still lose card processing. Direct-to-fan talent (Aisha Nasser, Noa Pell) feel this first. Counsel Day treats network rules as a third rail beside statute and state AV law.\n\nNot legal advice; network bulletins change without notice.",
    tags: ["payments", "mastercard", "visa", "consent", "private-rules"],
    status: "In force (network)",
    facts: [
      { label: "Nature", value: "Private network rules" },
      { label: "Pressure", value: "Acquirers & platforms" },
    ],
    related: [
      { kind: "law", id: "usc-2257" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "performers", id: "aisha-nasser" },
    ],
    source: "public",
  },
  {
    id: "usc-1591",
    kind: "law",
    name: "18 U.S.C. § 1591",
    subtitle: "Sex trafficking",
    citation: "18 U.S.C. § 1591",
    jurisdiction: "United States (federal)",
    summary:
      "Federal sex-trafficking statute. Adult production of consensual work by adults is not trafficking; platforms and producers still train to this line because FOSTA made the civil shadow longer.",
    body: "Section 1591 criminalizes sex trafficking of children and of adults by force, fraud, or coercion. Consensual adult production, correctly documented, is a different activity. The industry indexes 1591 because FOSTA-SESTA created civil exposure for platforms that host or promote violations, and because reputable houses treat recruitment, housing, and immigration of talent as a compliance problem, not a vibe.\n\nfleshsesh does not provide investigative how-to. If you need to report trafficking, use law enforcement and the National Human Trafficking Hotline (1-888-373-7888).\n\nNot legal advice.",
    tags: ["federal", "criminal", "trafficking"],
    status: "In force",
    facts: [
      { label: "Citation", value: "18 U.S.C. § 1591" },
      { label: "Hotline", value: "1-888-373-7888" },
    ],
    related: [
      { kind: "law", id: "fosta-sesta" },
      { kind: "companies", id: "fsc" },
      { kind: "companies", id: "asacp" },
    ],
    source: "public",
  },
  {
    id: "right-of-publicity",
    kind: "law",
    name: "Right of publicity",
    subtitle: "Name, image, likeness",
    jurisdiction: "U.S. states (common law & statute)",
    summary:
      "State-law right to control commercial use of one's identity. Performer contracts, clips used in trailers, and deepfakes all run through it — alongside copyright and TAKE IT DOWN.",
    body: "California, New York, and others recognize a right of publicity. Adult performers license name, image, and likeness in performing agreements; problems arise with scrapes, compilation tubes, lookalike marketing, and unauthorized AI. TAKE IT DOWN is a federal removal tool for intimate imagery; publicity is the civil claim for commercial identity.\n\nNot legal advice. Choice of law matters.",
    tags: ["state", "publicity", "nil", "contracts"],
    status: "Varies by state",
    facts: [
      { label: "Nature", value: "State law" },
      { label: "Neighbors", value: "Copyright, TAKE IT DOWN" },
    ],
    related: [
      { kind: "law", id: "take-it-down" },
      { kind: "law", id: "work-for-hire" },
    ],
    source: "public",
  },
  {
    id: "dmca-512",
    kind: "law",
    name: "DMCA § 512",
    subtitle: "Notice-and-takedown",
    citation: "17 U.S.C. § 512",
    jurisdiction: "United States (federal)",
    summary:
      "Safe harbor for online service providers that expeditiously remove allegedly infringing material after a valid copyright notice. Standard path for stolen scenes and scraped Vellum posts.",
    body: "Section 512 is copyright procedure, not 2257 and not TAKE IT DOWN. A studio or creator sends a notice identifying the work, the infringing URL, and a statement under penalty of perjury; a qualifying host that removes expeditiously keeps the safe harbor.\n\nAurelia Network lists a DMCA agent. TAKE IT DOWN now sits beside 512 for nonconsensual intimate imagery that may or may not be a copyright of the victim.\n\nNot legal advice.",
    tags: ["federal", "copyright", "dmca", "platforms"],
    status: "In force",
    facts: [
      { label: "Citation", value: "17 U.S.C. § 512" },
      { label: "Hook", value: "Registered DMCA agent" },
    ],
    related: [
      { kind: "law", id: "take-it-down" },
      { kind: "law", id: "section-230" },
      { kind: "companies", id: "aurelia-network" },
    ],
    source: "public",
  },
  {
    id: "work-for-hire",
    kind: "law",
    name: "Work made for hire & performer deals",
    subtitle: "Copyright and contracts",
    citation: "17 U.S.C. § 101; state contract law",
    jurisdiction: "United States",
    summary:
      "Who owns the master, the stills, the stage name, and the platform upload. Default copyright rules plus the four-page performer agreement that actually runs the set.",
    body: "U.S. copyright vests in the author unless a work is made for hire (employee in the scope of employment, or a specially commissioned work in a statutory category with a signed agreement) or is assigned. Adult sets often rely on performer agreements that assign copyright, license publicity, and confirm 2257 cooperation and STI protocols.\n\nCalifornia classification (A.B. 5) can cut against a clean work-for-hire employee story. Direct-to-fan talent who shoot themselves usually own the copyright unless they signed it away to a platform — most platforms take a license, not an assignment.\n\nNot legal advice. Do not shoot without a signed deal and a 2257 file.",
    tags: ["copyright", "contracts", "performers"],
    status: "Background law",
    facts: [
      { label: "Copyright", value: "17 U.S.C. § 101" },
      { label: "Labor overlay", value: "A.B. 5 in California" },
    ],
    related: [
      { kind: "law", id: "ab5-classification" },
      { kind: "law", id: "right-of-publicity" },
      { kind: "law", id: "usc-2257" },
    ],
    source: "public",
  },
];
