import type { Entity } from "./types";

export const industry: Entity[] = [
  // ── Companies ──────────────────────────────────────────────
  {
    id: "helix-house",
    kind: "companies",
    name: "Helix House",
    subtitle: "Premium studio",
    summary:
      "Los Angeles house known for director-led features, long contracts, and a closed 2257 desk. Flagship imprint of the contemporary West Coast scene.",
    body: "Founded in 2012 in Silver Lake, Helix House produces a short slate of high-budget features and a standing series, Glass Harbor. The company keeps a staff custodian of records, will not shoot without picture identification on file, and books through Redwood Talent and Meridian Casting. Contract talent typically sign two-year terms with first-look on directing.",
    tags: ["studio", "los-angeles", "features", "2257"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2012" },
      { label: "HQ", value: "Silver Lake, Los Angeles" },
      { label: "Imprint", value: "Features & series" },
      { label: "Custodian", value: "On-staff, inspected" },
    ],
    related: [
      { kind: "productions", id: "glass-harbor", label: "Flagship series" },
      { kind: "productions", id: "wintering", label: "Feature" },
      { kind: "agents", id: "mara-ellison" },
      { kind: "law", id: "usc-2257" },
    ],
    socials: [
      { platform: "X", handle: "@helixhouse" },
      { platform: "Instagram", handle: "@helixhouse" },
      { platform: "Site", handle: "helix.house" },
    ],
    source: "index",
  },
  {
    id: "northstar-pictures",
    kind: "companies",
    name: "Northstar Pictures",
    subtitle: "Feature studio",
    summary:
      "Narrative-first studio in the San Fernando Valley. Known for long-form features, union-style call sheets, and Palisade nominations.",
    body: "Northstar treats adult features as a production discipline: department heads, rehearsal days, and a published 2257 statement on every title card. Distributes through Eastbound. Several directors (Wren Solis, Evander Crowe) move between Northstar and Nightjar.",
    tags: ["studio", "features", "valley", "narrative"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2008" },
      { label: "HQ", value: "Van Nuys, California" },
      { label: "Distribution", value: "Eastbound" },
    ],
    related: [
      { kind: "productions", id: "the-night-ledger" },
      { kind: "productions", id: "eastern-standard" },
      { kind: "companies", id: "eastbound" },
      { kind: "performers", id: "wren-solis" },
    ],
    socials: [{ platform: "X", handle: "@northstarpix" }],
    source: "index",
  },
  {
    id: "nightjar-films",
    kind: "companies",
    name: "Nightjar Films",
    subtitle: "Auteur imprint",
    summary:
      "Director-owned imprint. Small crews, location work, and a roster of performers who also direct.",
    tags: ["studio", "indie", "directors"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2018" },
      { label: "Model", value: "Director-owned" },
    ],
    related: [
      { kind: "performers", id: "isla-vane" },
      { kind: "performers", id: "wren-solis" },
      { kind: "productions", id: "low-light" },
      { kind: "productions", id: "second-unit" },
      { kind: "events", id: "nightjar-forum-2026" },
    ],
    socials: [{ platform: "Instagram", handle: "@nightjarfilms" }],
    source: "index",
  },
  {
    id: "afterlight-media",
    kind: "companies",
    name: "Afterlight Media",
    subtitle: "European house",
    summary:
      "Berlin studio and sales agent. Shoots in German, French, and English; handles EU DSA age-assurance for its own storefront.",
    tags: ["studio", "berlin", "europe", "dsa"],
    region: "Berlin",
    status: "Active",
    facts: [
      { label: "Founded", value: "2014" },
      { label: "HQ", value: "Neukölln, Berlin" },
      { label: "Markets", value: "EU, UK, North America" },
    ],
    related: [
      { kind: "performers", id: "omar-leclerc" },
      { kind: "performers", id: "tamsin-rowe" },
      { kind: "agents", id: "sabine-kohler" },
      { kind: "productions", id: "corridor" },
      { kind: "events", id: "venus-berlin-2026" },
      { kind: "law", id: "eu-dsa" },
    ],
    socials: [{ platform: "X", handle: "@afterlightmedia" }],
    source: "index",
  },
  {
    id: "pine-vale",
    kind: "companies",
    name: "Pine & Vale",
    subtitle: "Boutique studio",
    summary:
      "Vancouver boutique. Short-run series, stills-led campaigns, and a reputation for performer-directors.",
    tags: ["studio", "vancouver", "boutique"],
    region: "Vancouver",
    status: "Active",
    facts: [
      { label: "Founded", value: "2016" },
      { label: "HQ", value: "Vancouver, BC" },
    ],
    related: [
      { kind: "performers", id: "maren-dahl" },
      { kind: "performers", id: "sienna-park" },
      { kind: "productions", id: "salt-and-copper" },
    ],
    socials: [{ platform: "Instagram", handle: "@pineandvale" }],
    source: "index",
  },
  {
    id: "vellum-digital",
    kind: "companies",
    name: "Vellum",
    subtitle: "Direct-to-fan platform",
    summary:
      "Subscription platform for independent adult creators. Secondary-producer 2257 posture; creators remain primary producers of their own work.",
    body: "Vellum is the catalog's stand-in for the direct-to-fan stack: subscriptions, PPV, and tipping. The company stores copies of creator IDs as a secondary producer and requires a 2257 statement on every profile. TAKE IT DOWN Act notice-and-removal is published in the footer, with a 48-hour SLA.",
    tags: ["platform", "direct-to-fan", "2257", "take-it-down"],
    region: "United States",
    status: "Active",
    facts: [
      { label: "Launched", value: "2019" },
      { label: "Role", value: "Secondary producer" },
      { label: "Removal SLA", value: "48 hours" },
    ],
    related: [
      { kind: "performers", id: "noa-pell" },
      { kind: "performers", id: "aisha-nasser" },
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "take-it-down" },
      { kind: "law", id: "card-networks" },
    ],
    socials: [
      { platform: "X", handle: "@vellum" },
      { platform: "Site", handle: "vellum.example" },
    ],
    source: "index",
  },
  {
    id: "cobalt-interactive",
    kind: "companies",
    name: "Cobalt",
    subtitle: "Live platform",
    summary:
      "Live-cam and ticketed shows. Age-gates at signup; geo-blocks jurisdictions with strict AV statutes when it cannot verify.",
    tags: ["platform", "live", "age-assurance"],
    region: "United States",
    status: "Active",
    facts: [
      { label: "Launched", value: "2011" },
      { label: "Format", value: "Live + tickets" },
    ],
    related: [
      { kind: "performers", id: "kade-morin" },
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "state-av-laws" },
    ],
    socials: [{ platform: "X", handle: "@cobaltlive" }],
    source: "index",
  },
  {
    id: "aurelia-network",
    kind: "companies",
    name: "Aurelia Network",
    subtitle: "Aggregator",
    summary:
      "Licensed tube and clip aggregator. DMCA agent on file; 2257 statements inherited from studio partners; geo-fencing after FSC v. Paxton.",
    tags: ["platform", "tube", "dmca", "geo-fence"],
    region: "Cyprus / United States",
    status: "Active",
    facts: [
      { label: "Launched", value: "2007" },
      { label: "Model", value: "Licensed aggregator" },
    ],
    related: [
      { kind: "companies", id: "eastbound" },
      { kind: "law", id: "dmca-512" },
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "fosta-sesta" },
    ],
    socials: [{ platform: "X", handle: "@aurelia" }],
    source: "index",
  },
  {
    id: "eastbound",
    kind: "companies",
    name: "Eastbound Distribution",
    subtitle: "Sales & distribution",
    summary:
      "North American sales agent for Helix, Northstar, Pine & Vale, and Afterlight's English-language slate.",
    tags: ["distributor", "sales"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2004" },
      { label: "HQ", value: "Hollywood, California" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "northstar-pictures" },
      { kind: "companies", id: "afterlight-media" },
      { kind: "events", id: "avn-expo-2026" },
    ],
    socials: [{ platform: "X", handle: "@eastboundhq" }],
    source: "index",
  },
  {
    id: "redwood-talent",
    kind: "companies",
    name: "Redwood Talent",
    subtitle: "Talent agency",
    summary:
      "Full-service agency for on-camera talent, directors, and a growing direct-to-fan book. Los Angeles with a Berlin desk via Sabine Köhler.",
    tags: ["agency", "representation"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2009" },
      { label: "Desks", value: "Los Angeles, Berlin" },
    ],
    related: [
      { kind: "agents", id: "mara-ellison" },
      { kind: "agents", id: "devon-reyes" },
      { kind: "companies", id: "helix-house" },
    ],
    socials: [{ platform: "Instagram", handle: "@redwoodtalent" }],
    source: "index",
  },
  {
    id: "meridian-casting",
    kind: "companies",
    name: "Meridian Casting",
    subtitle: "Casting",
    summary:
      "Casting office for features and series. Keeps a private 2257 pre-clear list; will not submit a performer without current identification on file.",
    tags: ["casting", "2257"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Founded", value: "2011" },
      { label: "Specialty", value: "Features & series" },
    ],
    related: [
      { kind: "agents", id: "jonah-peck" },
      { kind: "companies", id: "northstar-pictures" },
      { kind: "law", id: "usc-2257" },
    ],
    source: "index",
  },
  {
    id: "palisade-institute",
    kind: "companies",
    name: "Palisade Institute",
    subtitle: "Awards body",
    summary:
      "Trade academy behind the Palisade Honors. Publishes eligibility rules, a performer-safety pledge, and an annual craft ballot.",
    tags: ["awards", "trade-body"],
    region: "Las Vegas",
    status: "Active",
    facts: [
      { label: "Founded", value: "1999" },
      { label: "Flagship", value: "Palisade Honors" },
    ],
    related: [
      { kind: "events", id: "palisade-honors-2026" },
      { kind: "events", id: "avn-expo-2026" },
    ],
    socials: [{ platform: "X", handle: "@palisadehonors" }],
    source: "index",
  },
  {
    id: "counsel-group",
    kind: "companies",
    name: "Counsel Group",
    subtitle: "Industry counsel",
    summary:
      "Boutique firm for 2257 programs, performer contracts, platform terms, and state age-verification maps. Hosts Counsel Day.",
    tags: ["law-firm", "compliance", "2257"],
    region: "Los Angeles / Washington",
    status: "Active",
    facts: [
      { label: "Founded", value: "2006" },
      { label: "Desks", value: "Los Angeles, D.C." },
    ],
    related: [
      { kind: "events", id: "counsel-day-2026" },
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "take-it-down" },
    ],
    socials: [{ platform: "Site", handle: "counsel.group" }],
    source: "index",
  },
  {
    id: "copperline-pr",
    kind: "companies",
    name: "Copperline",
    subtitle: "Public relations",
    summary:
      "Trade PR and awards campaign shop. Books talent at expos and manages Palisade campaigns.",
    tags: ["pr", "awards"],
    region: "Los Angeles",
    status: "Active",
    facts: [{ label: "Founded", value: "2015" }],
    related: [
      { kind: "events", id: "avn-expo-2026" },
      { kind: "events", id: "xbiz-2026" },
      { kind: "companies", id: "palisade-institute" },
    ],
    source: "index",
  },
  {
    id: "fsc",
    kind: "companies",
    name: "Free Speech Coalition",
    subtitle: "Trade association",
    summary:
      "U.S. trade association for the adult industry. Plaintiff in Free Speech Coalition v. Paxton (2025). Advocacy, compliance education, and performer resources.",
    body: "The Free Speech Coalition is the principal U.S. trade group for adult producers, platforms, and performers. It litigates and lobbies on First Amendment, record-keeping, payment, and age-verification issues, and publishes compliance guidance for members. In 2025 it was the named petitioner in Free Speech Coalition v. Paxton, the Supreme Court case on Texas H.B. 1181.",
    tags: ["trade-body", "advocacy", "united-states", "public"],
    region: "United States",
    status: "Active",
    facts: [
      { label: "Founded", value: "1991" },
      { label: "Type", value: "Trade association" },
      { label: "Record", value: "FSC v. Paxton (2025)" },
    ],
    related: [
      { kind: "law", id: "fsc-v-paxton" },
      { kind: "law", id: "fosta-sesta" },
      { kind: "law", id: "usc-2257" },
      { kind: "companies", id: "asacp" },
    ],
    socials: [
      { platform: "X", handle: "@FreeSpeechFSC" },
      { platform: "Site", handle: "freespeechcoalition.com" },
    ],
    source: "public",
  },
  {
    id: "asacp",
    kind: "companies",
    name: "ASACP",
    subtitle: "Child-protection nonprofit",
    summary:
      "Association of Sites Advocating Child Protection. Independent nonprofit that fights child sexual abuse material online and runs a hotline used across the adult trade.",
    tags: ["nonprofit", "child-protection", "public"],
    region: "United States",
    status: "Active",
    facts: [
      { label: "Founded", value: "1996" },
      { label: "Type", value: "Nonprofit" },
    ],
    related: [
      { kind: "companies", id: "fsc" },
      { kind: "law", id: "usc-2257" },
    ],
    socials: [{ platform: "Site", handle: "asacp.org" }],
    source: "public",
  },

  // ── Agents ─────────────────────────────────────────────────
  {
    id: "mara-ellison",
    kind: "agents",
    name: "Mara Ellison",
    subtitle: "Partner, Redwood Talent",
    summary:
      "Books Helix House contracts and a select independent list. Known for long-term deals with first-look directing clauses.",
    tags: ["agent", "los-angeles", "contracts"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Agency", value: "Redwood Talent" },
      { label: "Desk", value: "On-camera & directors" },
      { label: "Since", value: "2013" },
    ],
    credits: [
      { role: "Represents", title: "Isla Vane", year: "2019–", kind: "performers", id: "isla-vane" },
      { role: "Represents", title: "Roman Calder", year: "2016–", kind: "performers", id: "roman-calder" },
      { role: "Represents", title: "Juniper Hale", year: "2021–", kind: "performers", id: "juniper-hale" },
      { role: "Represents", title: "Cassian Wolfe", year: "2018–", kind: "performers", id: "cassian-wolfe" },
    ],
    related: [
      { kind: "companies", id: "redwood-talent" },
      { kind: "companies", id: "helix-house" },
      { kind: "performers", id: "isla-vane" },
    ],
    socials: [{ platform: "X", handle: "@maraellison" }],
    source: "index",
  },
  {
    id: "devon-reyes",
    kind: "agents",
    name: "Devon Reyes",
    subtitle: "Agent, Redwood Talent",
    summary:
      "Direct-to-fan and crossover book. Places clients on Vellum and brokered the Pine & Vale Vancouver slate.",
    tags: ["agent", "direct-to-fan"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Agency", value: "Redwood Talent" },
      { label: "Desk", value: "Direct-to-fan" },
    ],
    credits: [
      { role: "Represents", title: "Noa Pell", year: "2022–", kind: "performers", id: "noa-pell" },
      { role: "Represents", title: "Aisha Nasser", year: "2023–", kind: "performers", id: "aisha-nasser" },
      { role: "Represents", title: "Sienna Park", year: "2020–", kind: "performers", id: "sienna-park" },
    ],
    related: [
      { kind: "companies", id: "redwood-talent" },
      { kind: "companies", id: "vellum-digital" },
    ],
    source: "index",
  },
  {
    id: "jonah-peck",
    kind: "agents",
    name: "Jonah Peck",
    subtitle: "Casting director, Meridian",
    summary:
      "Casts Northstar features and the Glass Harbor rotating company. Runs Meridian's 2257 pre-clear.",
    tags: ["casting", "features"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Office", value: "Meridian Casting" },
      { label: "Since", value: "2011" },
    ],
    related: [
      { kind: "companies", id: "meridian-casting" },
      { kind: "companies", id: "northstar-pictures" },
      { kind: "productions", id: "glass-harbor" },
    ],
    source: "index",
  },
  {
    id: "sabine-kohler",
    kind: "agents",
    name: "Sabine Köhler",
    subtitle: "EU desk, Redwood / Afterlight",
    summary:
      "Berlin-based booker for Afterlight and Redwood's European list. Places talent at Venus Berlin and handles DSA-facing storefront copy.",
    tags: ["agent", "berlin", "europe"],
    region: "Berlin",
    status: "Active",
    facts: [
      { label: "Desks", value: "Redwood Talent, Afterlight" },
      { label: "Market", value: "EU & UK" },
    ],
    credits: [
      { role: "Represents", title: "Omar Leclerc", year: "2017–", kind: "performers", id: "omar-leclerc" },
      { role: "Represents", title: "Tamsin Rowe", year: "2019–", kind: "performers", id: "tamsin-rowe" },
      { role: "Represents", title: "Felix Arden", year: "2021–", kind: "performers", id: "felix-arden" },
    ],
    related: [
      { kind: "companies", id: "afterlight-media" },
      { kind: "companies", id: "redwood-talent" },
      { kind: "events", id: "venus-berlin-2026" },
    ],
    socials: [{ platform: "Instagram", handle: "@sabinekohler" }],
    source: "index",
  },
  {
    id: "nina-braswell",
    kind: "agents",
    name: "Nina Braswell",
    subtitle: "Independent manager",
    summary:
      "Manager for performer-directors and a small trans roster. Advises on TAKE IT DOWN notices and platform terms.",
    tags: ["manager", "independent"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "Practice", value: "Independent management" },
      { label: "Since", value: "2020" },
    ],
    credits: [
      { role: "Manages", title: "Wren Solis", year: "2020–", kind: "performers", id: "wren-solis" },
      { role: "Manages", title: "Percy Lane", year: "2021–", kind: "performers", id: "percy-lane" },
      { role: "Manages", title: "Ellis Hart", year: "2022–", kind: "performers", id: "ellis-hart" },
    ],
    related: [
      { kind: "performers", id: "wren-solis" },
      { kind: "law", id: "take-it-down" },
    ],
    source: "index",
  },
  {
    id: "haruki-mori",
    kind: "agents",
    name: "Haruki Mori",
    subtitle: "Pacific booker",
    summary:
      "Independent booker splitting Tokyo and Los Angeles. Places bilingual talent on Helix and Afterlight English-language days.",
    tags: ["agent", "tokyo", "los-angeles"],
    region: "Tokyo / Los Angeles",
    status: "Active",
    facts: [
      { label: "Practice", value: "Independent" },
      { label: "Languages", value: "Japanese, English" },
    ],
    credits: [
      { role: "Represents", title: "Liora Chen", year: "2020–", kind: "performers", id: "liora-chen" },
      { role: "Represents", title: "Sienna Park", year: "2024–", kind: "performers", id: "sienna-park" },
    ],
    related: [
      { kind: "performers", id: "liora-chen" },
      { kind: "companies", id: "helix-house" },
    ],
    source: "index",
  },

  // ── Performers ─────────────────────────────────────────────
  {
    id: "isla-vane",
    kind: "performers",
    name: "Isla Vane",
    subtitle: "Performer · director",
    aka: ["I. Vane"],
    summary:
      "Helix House contract 2020–2024. Palisade Best New Star, 2020. Now directing for Nightjar and releasing independently on Vellum.",
    body: "Isla Vane first credited in 2019 and signed with Helix House the following year. Four Palisade nominations followed, including a Best New Star win. After her contract lapsed she moved into direction on Low Light and keeps a direct-to-fan studio. Represented by Mara Ellison. All credits are of a working adult; first year of professional work is 2019.",
    tags: ["performer", "director", "los-angeles", "helix"],
    region: "Los Angeles",
    status: "Independent",
    facts: [
      { label: "First credited", value: "2019" },
      { label: "Contract", value: "Helix House, 2020–2024" },
      { label: "Representation", value: "Mara Ellison, Redwood" },
      { label: "Awards", value: "Palisade Best New Star, 2020" },
    ],
    credits: [
      { role: "Lead", title: "Glass Harbor", year: "2020–24", kind: "productions", id: "glass-harbor" },
      { role: "Lead", title: "Wintering", year: "2022", kind: "productions", id: "wintering" },
      { role: "Director", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
      { role: "Lead", title: "A Room in Silverlake", year: "2023", kind: "productions", id: "silverlake" },
    ],
    related: [
      { kind: "agents", id: "mara-ellison" },
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "nightjar-films" },
      { kind: "productions", id: "low-light" },
    ],
    socials: [
      { platform: "Instagram", handle: "@islavane" },
      { platform: "X", handle: "@islavane" },
      { platform: "Vellum", handle: "isla" },
    ],
    source: "index",
  },
  {
    id: "roman-calder",
    kind: "performers",
    name: "Roman Calder",
    subtitle: "Performer",
    summary:
      "Valley veteran. Northstar and Helix regular; Palisade Best Supporting, 2023. Brother of Bo Calder.",
    tags: ["performer", "los-angeles", "veteran"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2014" },
      { label: "Representation", value: "Mara Ellison, Redwood" },
      { label: "Awards", value: "Palisade Best Supporting, 2023" },
    ],
    credits: [
      { role: "Lead", title: "The Night Ledger", year: "2021", kind: "productions", id: "the-night-ledger" },
      { role: "Supporting", title: "Glass Harbor", year: "2021–24", kind: "productions", id: "glass-harbor" },
      { role: "Lead", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
    ],
    related: [
      { kind: "performers", id: "bo-calder", label: "Sibling" },
      { kind: "agents", id: "mara-ellison" },
      { kind: "companies", id: "northstar-pictures" },
    ],
    socials: [{ platform: "X", handle: "@romancalder" }],
    source: "index",
  },
  {
    id: "juniper-hale",
    kind: "performers",
    name: "Juniper Hale",
    subtitle: "Performer",
    summary:
      "Helix contract talent. Breakthrough in A Room in Silverlake; Palisade nominee, 2024.",
    tags: ["performer", "helix", "contract"],
    region: "Los Angeles",
    status: "Contract",
    facts: [
      { label: "First credited", value: "2021" },
      { label: "Contract", value: "Helix House, 2022–" },
      { label: "Representation", value: "Mara Ellison, Redwood" },
    ],
    credits: [
      { role: "Lead", title: "A Room in Silverlake", year: "2023", kind: "productions", id: "silverlake" },
      { role: "Lead", title: "Glass Harbor", year: "2023–", kind: "productions", id: "glass-harbor" },
      { role: "Supporting", title: "Wintering", year: "2022", kind: "productions", id: "wintering" },
    ],
    related: [
      { kind: "agents", id: "mara-ellison" },
      { kind: "companies", id: "helix-house" },
      { kind: "performers", id: "isla-vane" },
    ],
    socials: [
      { platform: "Instagram", handle: "@juniperhale" },
      { platform: "Vellum", handle: "juniper" },
    ],
    source: "index",
  },
  {
    id: "mateo-ruiz",
    kind: "performers",
    name: "Mateo Ruiz",
    subtitle: "Performer · stills",
    summary:
      "Performer and stills photographer. Credits at Helix and Pine & Vale; campaigns for Copperline.",
    tags: ["performer", "photographer"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2018" },
      { label: "Also", value: "Stills & campaigns" },
    ],
    credits: [
      { role: "Lead", title: "Salt & Copper", year: "2023", kind: "productions", id: "salt-and-copper" },
      { role: "Supporting", title: "Glass Harbor", year: "2022", kind: "productions", id: "glass-harbor" },
    ],
    related: [
      { kind: "companies", id: "pine-vale" },
      { kind: "companies", id: "copperline-pr" },
    ],
    socials: [{ platform: "Instagram", handle: "@mateoruizstill" }],
    source: "index",
  },
  {
    id: "sable-quinn",
    kind: "performers",
    name: "Sable Quinn",
    subtitle: "Performer",
    summary:
      "Northstar exclusive 2019–2023. Known for long-form features; now splitting time between direction and Vellum.",
    tags: ["performer", "northstar", "features"],
    region: "Los Angeles",
    status: "Independent",
    facts: [
      { label: "First credited", value: "2016" },
      { label: "Exclusive", value: "Northstar, 2019–2023" },
    ],
    credits: [
      { role: "Lead", title: "The Night Ledger", year: "2021", kind: "productions", id: "the-night-ledger" },
      { role: "Lead", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "performers", id: "roman-calder" },
    ],
    socials: [
      { platform: "X", handle: "@sablequinn" },
      { platform: "Vellum", handle: "sable" },
    ],
    source: "index",
  },
  {
    id: "theo-marsh",
    kind: "performers",
    name: "Theo Marsh",
    subtitle: "Performer",
    summary:
      "Helix and Nightjar. Palisade ensemble nominee with the Glass Harbor company, 2024.",
    tags: ["performer", "helix"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2020" },
      { label: "Representation", value: "Redwood Talent" },
    ],
    credits: [
      { role: "Ensemble", title: "Glass Harbor", year: "2021–", kind: "productions", id: "glass-harbor" },
      { role: "Supporting", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "productions", id: "glass-harbor" },
    ],
    socials: [{ platform: "Instagram", handle: "@theomarsh" }],
    source: "index",
  },
  {
    id: "liora-chen",
    kind: "performers",
    name: "Liora Chen",
    subtitle: "Performer",
    summary:
      "Bilingual talent booked between Los Angeles and Tokyo. Helix guest lead; Afterlight English-language days.",
    tags: ["performer", "tokyo", "los-angeles"],
    region: "Tokyo / Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2020" },
      { label: "Representation", value: "Haruki Mori" },
      { label: "Languages", value: "English, Japanese" },
    ],
    credits: [
      { role: "Guest lead", title: "Glass Harbor", year: "2024", kind: "productions", id: "glass-harbor" },
      { role: "Lead", title: "Corridor", year: "2025", kind: "productions", id: "corridor" },
    ],
    related: [
      { kind: "agents", id: "haruki-mori" },
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "afterlight-media" },
    ],
    socials: [{ platform: "Instagram", handle: "@liorachen" }],
    source: "index",
  },
  {
    id: "cassian-wolfe",
    kind: "performers",
    name: "Cassian Wolfe",
    subtitle: "Performer",
    summary:
      "Helix contract, 2018–. Palisade Best Lead, 2022. Frequent pairing with Isla Vane and Juniper Hale.",
    tags: ["performer", "helix", "contract"],
    region: "Los Angeles",
    status: "Contract",
    facts: [
      { label: "First credited", value: "2017" },
      { label: "Contract", value: "Helix House, 2018–" },
      { label: "Representation", value: "Mara Ellison, Redwood" },
      { label: "Awards", value: "Palisade Best Lead, 2022" },
    ],
    credits: [
      { role: "Lead", title: "Glass Harbor", year: "2018–", kind: "productions", id: "glass-harbor" },
      { role: "Lead", title: "Wintering", year: "2022", kind: "productions", id: "wintering" },
      { role: "Lead", title: "A Room in Silverlake", year: "2023", kind: "productions", id: "silverlake" },
    ],
    related: [
      { kind: "agents", id: "mara-ellison" },
      { kind: "companies", id: "helix-house" },
      { kind: "performers", id: "isla-vane" },
    ],
    socials: [
      { platform: "X", handle: "@cassianwolfe" },
      { platform: "Instagram", handle: "@cassianwolfe" },
    ],
    source: "index",
  },
  {
    id: "noa-pell",
    kind: "performers",
    name: "Noa Pell",
    subtitle: "Creator · performer",
    summary:
      "Direct-to-fan first. Vellum top-tier; selective studio days through Devon Reyes. Speaks on platform terms at Ledger Week.",
    tags: ["creator", "direct-to-fan", "vellum"],
    region: "Austin",
    status: "Independent",
    facts: [
      { label: "First credited", value: "2021" },
      { label: "Platform", value: "Vellum" },
      { label: "Representation", value: "Devon Reyes, Redwood" },
    ],
    credits: [
      { role: "Creator", title: "Vellum studio", year: "2021–", kind: "companies", id: "vellum-digital" },
      { role: "Guest", title: "Second Unit", year: "2025", kind: "productions", id: "second-unit" },
    ],
    related: [
      { kind: "agents", id: "devon-reyes" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "events", id: "ledger-week-2026" },
    ],
    socials: [
      { platform: "Vellum", handle: "noa" },
      { platform: "X", handle: "@noapell" },
    ],
    source: "index",
  },
  {
    id: "evander-crowe",
    kind: "performers",
    name: "Evander Crowe",
    subtitle: "Director · performer",
    summary:
      "Director of The Night Ledger and Eastern Standard. Occasional on-camera credit. Nightjar partner.",
    tags: ["director", "performer", "northstar"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2012" },
      { label: "Primary", value: "Direction" },
    ],
    credits: [
      { role: "Director", title: "The Night Ledger", year: "2021", kind: "productions", id: "the-night-ledger" },
      { role: "Director", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
      { role: "Director", title: "The Palisade Brief", year: "2025", kind: "productions", id: "palisade-brief" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "companies", id: "nightjar-films" },
    ],
    socials: [{ platform: "X", handle: "@evandercrowe" }],
    source: "index",
  },
  {
    id: "wren-solis",
    kind: "performers",
    name: "Wren Solis",
    subtitle: "Director · performer",
    summary:
      "Performer-director. Nightjar partner; directed Second Unit. Managed by Nina Braswell.",
    tags: ["director", "performer", "nightjar"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2015" },
      { label: "Management", value: "Nina Braswell" },
    ],
    credits: [
      { role: "Director", title: "Second Unit", year: "2025", kind: "productions", id: "second-unit" },
      { role: "Lead", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
      { role: "Supporting", title: "The Night Ledger", year: "2021", kind: "productions", id: "the-night-ledger" },
    ],
    related: [
      { kind: "agents", id: "nina-braswell" },
      { kind: "companies", id: "nightjar-films" },
      { kind: "performers", id: "isla-vane" },
    ],
    socials: [
      { platform: "Instagram", handle: "@wrensolis" },
      { platform: "X", handle: "@wrensolis" },
    ],
    source: "index",
  },
  {
    id: "dax-harlan",
    kind: "performers",
    name: "Dax Harlan",
    subtitle: "Performer",
    summary:
      "Northstar and Helix supporting player. Palisade crafts nominee (ensemble), 2024.",
    tags: ["performer", "supporting"],
    region: "Los Angeles",
    status: "Active",
    facts: [{ label: "First credited", value: "2019" }],
    credits: [
      { role: "Supporting", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
      { role: "Ensemble", title: "Glass Harbor", year: "2022–", kind: "productions", id: "glass-harbor" },
    ],
    related: [{ kind: "companies", id: "northstar-pictures" }],
    socials: [{ platform: "Instagram", handle: "@daxharlan" }],
    source: "index",
  },
  {
    id: "amara-voss",
    kind: "performers",
    name: "Amara Voss",
    subtitle: "Performer",
    summary:
      "Pine & Vale contract, Vancouver. Lead of Salt & Copper. Occasional Los Angeles days.",
    tags: ["performer", "vancouver", "pine-vale"],
    region: "Vancouver",
    status: "Contract",
    facts: [
      { label: "First credited", value: "2020" },
      { label: "Contract", value: "Pine & Vale, 2021–" },
    ],
    credits: [
      { role: "Lead", title: "Salt & Copper", year: "2023", kind: "productions", id: "salt-and-copper" },
      { role: "Guest", title: "Glass Harbor", year: "2024", kind: "productions", id: "glass-harbor" },
    ],
    related: [
      { kind: "companies", id: "pine-vale" },
      { kind: "performers", id: "maren-dahl" },
    ],
    socials: [{ platform: "Instagram", handle: "@amaravoss" }],
    source: "index",
  },
  {
    id: "nico-bell",
    kind: "performers",
    name: "Nico Bell",
    subtitle: "Performer",
    summary:
      "Helix and Cobalt. Live-ticketed shows plus studio days; talks age-assurance at Counsel Day.",
    tags: ["performer", "live", "cobalt"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2018" },
      { label: "Live", value: "Cobalt" },
    ],
    credits: [
      { role: "Host", title: "Cobalt nights", year: "2019–", kind: "companies", id: "cobalt-interactive" },
      { role: "Supporting", title: "A Room in Silverlake", year: "2023", kind: "productions", id: "silverlake" },
    ],
    related: [
      { kind: "companies", id: "cobalt-interactive" },
      { kind: "events", id: "counsel-day-2026" },
    ],
    socials: [
      { platform: "Cobalt", handle: "nicobell" },
      { platform: "X", handle: "@nicobell" },
    ],
    source: "index",
  },
  {
    id: "percy-lane",
    kind: "performers",
    name: "Persephone Lane",
    subtitle: "Performer",
    aka: ["Percy Lane"],
    summary:
      "Trans performer-director. Nightjar and independent Vellum. Managed by Nina Braswell. Palisade Breakthrough, 2023.",
    tags: ["performer", "director", "trans"],
    region: "Los Angeles",
    status: "Independent",
    facts: [
      { label: "First credited", value: "2020" },
      { label: "Management", value: "Nina Braswell" },
      { label: "Awards", value: "Palisade Breakthrough, 2023" },
    ],
    credits: [
      { role: "Lead", title: "Second Unit", year: "2025", kind: "productions", id: "second-unit" },
      { role: "Lead", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
    ],
    related: [
      { kind: "agents", id: "nina-braswell" },
      { kind: "companies", id: "nightjar-films" },
      { kind: "performers", id: "wren-solis" },
    ],
    socials: [
      { platform: "Instagram", handle: "@percylane" },
      { platform: "Vellum", handle: "percy" },
    ],
    source: "index",
  },
  {
    id: "kade-morin",
    kind: "performers",
    name: "Kade Morin",
    subtitle: "Performer · live",
    summary:
      "Cobalt headliner who crossed into Helix guest days. Direct-to-fan on Vellum.",
    tags: ["performer", "live", "cobalt"],
    region: "Miami",
    status: "Active",
    facts: [
      { label: "First credited", value: "2019" },
      { label: "Live", value: "Cobalt" },
    ],
    credits: [
      { role: "Headliner", title: "Cobalt", year: "2019–", kind: "companies", id: "cobalt-interactive" },
      { role: "Guest", title: "Glass Harbor", year: "2023", kind: "productions", id: "glass-harbor" },
    ],
    related: [
      { kind: "companies", id: "cobalt-interactive" },
      { kind: "companies", id: "vellum-digital" },
    ],
    socials: [
      { platform: "Cobalt", handle: "kade" },
      { platform: "Vellum", handle: "kade" },
    ],
    source: "index",
  },
  {
    id: "yara-okonkwo",
    kind: "performers",
    name: "Yara Okonkwo",
    subtitle: "Performer",
    summary:
      "Northstar lead. Eastern Standard opposite Roman Calder. Palisade Best Lead nominee, 2025.",
    tags: ["performer", "northstar", "features"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2018" },
      { label: "Awards", value: "Palisade Best Lead nominee, 2025" },
    ],
    credits: [
      { role: "Lead", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
      { role: "Lead", title: "The Palisade Brief", year: "2025", kind: "productions", id: "palisade-brief" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "performers", id: "roman-calder" },
    ],
    socials: [
      { platform: "Instagram", handle: "@yaraokonkwo" },
      { platform: "X", handle: "@yaraokonkwo" },
    ],
    source: "index",
  },
  {
    id: "ellis-hart",
    kind: "performers",
    name: "Ellis Hart",
    subtitle: "Performer",
    summary:
      "Non-binary performer. Nightjar and Vellum. Palisade ensemble, 2025.",
    tags: ["performer", "nightjar"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2022" },
      { label: "Management", value: "Nina Braswell" },
    ],
    credits: [
      { role: "Ensemble", title: "Second Unit", year: "2025", kind: "productions", id: "second-unit" },
      { role: "Supporting", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
    ],
    related: [
      { kind: "agents", id: "nina-braswell" },
      { kind: "companies", id: "nightjar-films" },
    ],
    socials: [
      { platform: "Instagram", handle: "@ellishart" },
      { platform: "Vellum", handle: "ellis" },
    ],
    source: "index",
  },
  {
    id: "maren-dahl",
    kind: "performers",
    name: "Maren Dahl",
    subtitle: "Performer · director",
    summary:
      "Pine & Vale partner in Vancouver. Directed Salt & Copper; stills background.",
    tags: ["performer", "director", "vancouver"],
    region: "Vancouver",
    status: "Active",
    facts: [
      { label: "First credited", value: "2016" },
      { label: "House", value: "Pine & Vale" },
    ],
    credits: [
      { role: "Director / lead", title: "Salt & Copper", year: "2023", kind: "productions", id: "salt-and-copper" },
    ],
    related: [
      { kind: "companies", id: "pine-vale" },
      { kind: "performers", id: "amara-voss" },
    ],
    socials: [{ platform: "Instagram", handle: "@marendahl" }],
    source: "index",
  },
  {
    id: "felix-arden",
    kind: "performers",
    name: "Felix Arden",
    subtitle: "Performer",
    summary:
      "Afterlight contract, Berlin. English- and German-language credits. Venus Berlin regular.",
    tags: ["performer", "berlin", "afterlight"],
    region: "Berlin",
    status: "Contract",
    facts: [
      { label: "First credited", value: "2021" },
      { label: "Representation", value: "Sabine Köhler" },
    ],
    credits: [
      { role: "Lead", title: "Corridor", year: "2025", kind: "productions", id: "corridor" },
    ],
    related: [
      { kind: "agents", id: "sabine-kohler" },
      { kind: "companies", id: "afterlight-media" },
      { kind: "events", id: "venus-berlin-2026" },
    ],
    socials: [{ platform: "Instagram", handle: "@felixarden" }],
    source: "index",
  },
  {
    id: "sienna-park",
    kind: "performers",
    name: "Sienna Park",
    subtitle: "Performer",
    summary:
      "Pine & Vale and Helix guest. Split representation: Devon Reyes (D2F) and Haruki Mori (Pacific studio days).",
    tags: ["performer", "vancouver", "los-angeles"],
    region: "Vancouver",
    status: "Active",
    facts: [
      { label: "First credited", value: "2020" },
      { label: "Representation", value: "Reyes / Mori" },
    ],
    credits: [
      { role: "Supporting", title: "Salt & Copper", year: "2023", kind: "productions", id: "salt-and-copper" },
      { role: "Guest", title: "Wintering", year: "2022", kind: "productions", id: "wintering" },
    ],
    related: [
      { kind: "agents", id: "devon-reyes" },
      { kind: "agents", id: "haruki-mori" },
      { kind: "companies", id: "pine-vale" },
    ],
    socials: [
      { platform: "Vellum", handle: "sienna" },
      { platform: "Instagram", handle: "@siennapark" },
    ],
    source: "index",
  },
  {
    id: "omar-leclerc",
    kind: "performers",
    name: "Omar Leclerc",
    subtitle: "Performer",
    summary:
      "Afterlight lead. French-English bilingual. Corridor opposite Liora Chen and Tamsin Rowe.",
    tags: ["performer", "berlin", "paris"],
    region: "Berlin / Paris",
    status: "Active",
    facts: [
      { label: "First credited", value: "2017" },
      { label: "Representation", value: "Sabine Köhler" },
    ],
    credits: [
      { role: "Lead", title: "Corridor", year: "2025", kind: "productions", id: "corridor" },
    ],
    related: [
      { kind: "agents", id: "sabine-kohler" },
      { kind: "companies", id: "afterlight-media" },
      { kind: "performers", id: "tamsin-rowe" },
    ],
    socials: [{ platform: "Instagram", handle: "@omarleclerc" }],
    source: "index",
  },
  {
    id: "tamsin-rowe",
    kind: "performers",
    name: "Tamsin Rowe",
    subtitle: "Performer · producer",
    summary:
      "Afterlight producer-performer. UK-born, Berlin-based. Advises on Online Safety Act storefront copy.",
    tags: ["performer", "producer", "berlin", "uk"],
    region: "Berlin",
    status: "Active",
    facts: [
      { label: "First credited", value: "2015" },
      { label: "Representation", value: "Sabine Köhler" },
    ],
    credits: [
      { role: "Producer / lead", title: "Corridor", year: "2025", kind: "productions", id: "corridor" },
    ],
    related: [
      { kind: "agents", id: "sabine-kohler" },
      { kind: "companies", id: "afterlight-media" },
      { kind: "law", id: "uk-online-safety" },
    ],
    socials: [
      { platform: "X", handle: "@tamsinrowe" },
      { platform: "Instagram", handle: "@tamsinrowe" },
    ],
    source: "index",
  },
  {
    id: "bo-calder",
    kind: "performers",
    name: "Bo Calder",
    subtitle: "Performer",
    summary:
      "Younger Calder. Helix guest and Vellum. First credited 2022.",
    tags: ["performer", "helix"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2022" },
      { label: "Family", value: "Sibling of Roman Calder" },
    ],
    credits: [
      { role: "Guest", title: "Glass Harbor", year: "2023", kind: "productions", id: "glass-harbor" },
      { role: "Supporting", title: "A Room in Silverlake", year: "2023", kind: "productions", id: "silverlake" },
    ],
    related: [
      { kind: "performers", id: "roman-calder", label: "Sibling" },
      { kind: "companies", id: "helix-house" },
    ],
    socials: [
      { platform: "Instagram", handle: "@bocalder" },
      { platform: "Vellum", handle: "bo" },
    ],
    source: "index",
  },
  {
    id: "rivka-stein",
    kind: "performers",
    name: "Rivka Stein",
    subtitle: "Performer · writer",
    summary:
      "Wrote The Palisade Brief for Northstar; occasional on-camera. Craft-side Palisade nominee, 2025.",
    tags: ["writer", "performer", "northstar"],
    region: "Los Angeles",
    status: "Active",
    facts: [
      { label: "First credited", value: "2017" },
      { label: "Primary", value: "Writing" },
    ],
    credits: [
      { role: "Writer", title: "The Palisade Brief", year: "2025", kind: "productions", id: "palisade-brief" },
      { role: "Writer", title: "Eastern Standard", year: "2024", kind: "productions", id: "eastern-standard" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "performers", id: "evander-crowe" },
    ],
    socials: [{ platform: "X", handle: "@rivkastein" }],
    source: "index",
  },
  {
    id: "gideon-vale",
    kind: "performers",
    name: "Gideon Vale",
    subtitle: "Performer",
    summary:
      "Nightjar ensemble. Supporting in Low Light and Second Unit.",
    tags: ["performer", "nightjar"],
    region: "Los Angeles",
    status: "Active",
    facts: [{ label: "First credited", value: "2021" }],
    credits: [
      { role: "Supporting", title: "Low Light", year: "2025", kind: "productions", id: "low-light" },
      { role: "Ensemble", title: "Second Unit", year: "2025", kind: "productions", id: "second-unit" },
    ],
    related: [{ kind: "companies", id: "nightjar-films" }],
    socials: [{ platform: "Instagram", handle: "@gideonvale" }],
    source: "index",
  },
  {
    id: "aisha-nasser",
    kind: "performers",
    name: "Aisha Nasser",
    subtitle: "Creator · performer",
    summary:
      "Vellum-native creator. Devon Reyes client. Speaks on card-network rules and 2257 for solo producers.",
    tags: ["creator", "direct-to-fan", "vellum"],
    region: "Chicago",
    status: "Independent",
    facts: [
      { label: "First credited", value: "2022" },
      { label: "Representation", value: "Devon Reyes, Redwood" },
    ],
    credits: [
      { role: "Creator", title: "Vellum studio", year: "2022–", kind: "companies", id: "vellum-digital" },
    ],
    related: [
      { kind: "agents", id: "devon-reyes" },
      { kind: "companies", id: "vellum-digital" },
      { kind: "law", id: "usc-2257" },
      { kind: "law", id: "card-networks" },
    ],
    socials: [
      { platform: "Vellum", handle: "aisha" },
      { platform: "X", handle: "@aishanasser" },
    ],
    source: "index",
  },
  {
    id: "cole-brennan",
    kind: "performers",
    name: "Cole Brennan",
    subtitle: "Performer",
    summary:
      "Helix supporting and Northstar features. Palisade ensemble, 2024.",
    tags: ["performer", "helix", "northstar"],
    region: "Los Angeles",
    status: "Active",
    facts: [{ label: "First credited", value: "2018" }],
    credits: [
      { role: "Supporting", title: "Wintering", year: "2022", kind: "productions", id: "wintering" },
      { role: "Supporting", title: "The Night Ledger", year: "2021", kind: "productions", id: "the-night-ledger" },
      { role: "Ensemble", title: "Glass Harbor", year: "2020–", kind: "productions", id: "glass-harbor" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "northstar-pictures" },
    ],
    socials: [{ platform: "Instagram", handle: "@colebrennan" }],
    source: "index",
  },

  // ── Productions ────────────────────────────────────────────
  {
    id: "glass-harbor",
    kind: "productions",
    name: "Glass Harbor",
    subtitle: "Series · Helix House",
    summary:
      "Helix House flagship series, 2018–. Rotating company, director-led episodes, Palisade ensemble winner 2024.",
    body: "Glass Harbor is the standing series against which Helix House contracts are measured. Episodes are credited to individual directors; Jonah Peck casts a rotating company. The 2024 Palisade ensemble award went to the Harbor company.",
    tags: ["series", "helix", "flagship"],
    region: "Los Angeles",
    status: "Ongoing",
    facts: [
      { label: "Studio", value: "Helix House" },
      { label: "Years", value: "2018–" },
      { label: "Casting", value: "Jonah Peck, Meridian" },
      { label: "Awards", value: "Palisade Ensemble, 2024" },
    ],
    credits: [
      { role: "Studio", title: "Helix House", year: "2018–", kind: "companies", id: "helix-house" },
      { role: "Casting", title: "Jonah Peck", year: "2018–", kind: "agents", id: "jonah-peck" },
      { role: "Lead", title: "Cassian Wolfe", year: "2018–", kind: "performers", id: "cassian-wolfe" },
      { role: "Lead", title: "Isla Vane", year: "2020–24", kind: "performers", id: "isla-vane" },
      { role: "Lead", title: "Juniper Hale", year: "2023–", kind: "performers", id: "juniper-hale" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "performers", id: "cassian-wolfe" },
      { kind: "performers", id: "isla-vane" },
    ],
    source: "index",
  },
  {
    id: "wintering",
    kind: "productions",
    name: "Wintering",
    subtitle: "Feature · Helix House",
    summary:
      "2022 Helix feature. Isla Vane and Cassian Wolfe. Palisade Best Feature nominee.",
    tags: ["feature", "helix"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Helix House" },
      { label: "Year", value: "2022" },
      { label: "Distribution", value: "Eastbound" },
    ],
    credits: [
      { role: "Lead", title: "Isla Vane", year: "2022", kind: "performers", id: "isla-vane" },
      { role: "Lead", title: "Cassian Wolfe", year: "2022", kind: "performers", id: "cassian-wolfe" },
      { role: "Supporting", title: "Juniper Hale", year: "2022", kind: "performers", id: "juniper-hale" },
      { role: "Supporting", title: "Cole Brennan", year: "2022", kind: "performers", id: "cole-brennan" },
    ],
    related: [
      { kind: "companies", id: "helix-house" },
      { kind: "companies", id: "eastbound" },
    ],
    source: "index",
  },
  {
    id: "silverlake",
    kind: "productions",
    name: "A Room in Silverlake",
    subtitle: "Feature · Helix House",
    summary:
      "2023 feature that made Juniper Hale. Location-heavy, stills by Mateo Ruiz.",
    tags: ["feature", "helix"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Helix House" },
      { label: "Year", value: "2023" },
    ],
    credits: [
      { role: "Lead", title: "Juniper Hale", year: "2023", kind: "performers", id: "juniper-hale" },
      { role: "Lead", title: "Isla Vane", year: "2023", kind: "performers", id: "isla-vane" },
      { role: "Lead", title: "Cassian Wolfe", year: "2023", kind: "performers", id: "cassian-wolfe" },
      { role: "Supporting", title: "Nico Bell", year: "2023", kind: "performers", id: "nico-bell" },
    ],
    related: [{ kind: "companies", id: "helix-house" }],
    source: "index",
  },
  {
    id: "the-night-ledger",
    kind: "productions",
    name: "The Night Ledger",
    subtitle: "Feature · Northstar",
    summary:
      "2021 Northstar feature directed by Evander Crowe. Palisade Best Feature, 2022.",
    tags: ["feature", "northstar", "award"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Northstar Pictures" },
      { label: "Year", value: "2021" },
      { label: "Director", value: "Evander Crowe" },
      { label: "Awards", value: "Palisade Best Feature, 2022" },
    ],
    credits: [
      { role: "Director", title: "Evander Crowe", year: "2021", kind: "performers", id: "evander-crowe" },
      { role: "Lead", title: "Sable Quinn", year: "2021", kind: "performers", id: "sable-quinn" },
      { role: "Lead", title: "Roman Calder", year: "2021", kind: "performers", id: "roman-calder" },
      { role: "Supporting", title: "Wren Solis", year: "2021", kind: "performers", id: "wren-solis" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "performers", id: "evander-crowe" },
    ],
    source: "index",
  },
  {
    id: "eastern-standard",
    kind: "productions",
    name: "Eastern Standard",
    subtitle: "Feature · Northstar",
    summary:
      "2024 Crowe/Stein collaboration. Yara Okonkwo and Roman Calder. Palisade Best Lead nominee (Okonkwo), 2025.",
    tags: ["feature", "northstar"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Northstar Pictures" },
      { label: "Year", value: "2024" },
      { label: "Director", value: "Evander Crowe" },
      { label: "Writer", value: "Rivka Stein" },
    ],
    credits: [
      { role: "Director", title: "Evander Crowe", year: "2024", kind: "performers", id: "evander-crowe" },
      { role: "Writer", title: "Rivka Stein", year: "2024", kind: "performers", id: "rivka-stein" },
      { role: "Lead", title: "Yara Okonkwo", year: "2024", kind: "performers", id: "yara-okonkwo" },
      { role: "Lead", title: "Roman Calder", year: "2024", kind: "performers", id: "roman-calder" },
    ],
    related: [{ kind: "companies", id: "northstar-pictures" }],
    source: "index",
  },
  {
    id: "palisade-brief",
    kind: "productions",
    name: "The Palisade Brief",
    subtitle: "Feature · Northstar",
    summary:
      "2025 Northstar title written by Rivka Stein. A feature about a counsel's office — meta, on purpose.",
    tags: ["feature", "northstar"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Northstar Pictures" },
      { label: "Year", value: "2025" },
    ],
    credits: [
      { role: "Director", title: "Evander Crowe", year: "2025", kind: "performers", id: "evander-crowe" },
      { role: "Writer", title: "Rivka Stein", year: "2025", kind: "performers", id: "rivka-stein" },
      { role: "Lead", title: "Yara Okonkwo", year: "2025", kind: "performers", id: "yara-okonkwo" },
    ],
    related: [
      { kind: "companies", id: "northstar-pictures" },
      { kind: "companies", id: "palisade-institute" },
    ],
    source: "index",
  },
  {
    id: "low-light",
    kind: "productions",
    name: "Low Light",
    subtitle: "Feature · Nightjar",
    summary:
      "Isla Vane's directing debut, 2025. Wren Solis and Percy Lane. Nightjar imprint.",
    tags: ["feature", "nightjar", "directing-debut"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Nightjar Films" },
      { label: "Year", value: "2025" },
      { label: "Director", value: "Isla Vane" },
    ],
    credits: [
      { role: "Director", title: "Isla Vane", year: "2025", kind: "performers", id: "isla-vane" },
      { role: "Lead", title: "Wren Solis", year: "2025", kind: "performers", id: "wren-solis" },
      { role: "Lead", title: "Persephone Lane", year: "2025", kind: "performers", id: "percy-lane" },
      { role: "Supporting", title: "Ellis Hart", year: "2025", kind: "performers", id: "ellis-hart" },
    ],
    related: [
      { kind: "companies", id: "nightjar-films" },
      { kind: "performers", id: "isla-vane" },
    ],
    source: "index",
  },
  {
    id: "second-unit",
    kind: "productions",
    name: "Second Unit",
    subtitle: "Feature · Nightjar",
    summary:
      "Wren Solis directs. Percy Lane, Ellis Hart, Noa Pell guest. 2025.",
    tags: ["feature", "nightjar"],
    region: "Los Angeles",
    status: "Released",
    facts: [
      { label: "Studio", value: "Nightjar Films" },
      { label: "Year", value: "2025" },
      { label: "Director", value: "Wren Solis" },
    ],
    credits: [
      { role: "Director", title: "Wren Solis", year: "2025", kind: "performers", id: "wren-solis" },
      { role: "Lead", title: "Persephone Lane", year: "2025", kind: "performers", id: "percy-lane" },
      { role: "Ensemble", title: "Ellis Hart", year: "2025", kind: "performers", id: "ellis-hart" },
      { role: "Guest", title: "Noa Pell", year: "2025", kind: "performers", id: "noa-pell" },
    ],
    related: [{ kind: "companies", id: "nightjar-films" }],
    source: "index",
  },
  {
    id: "corridor",
    kind: "productions",
    name: "Corridor",
    subtitle: "Feature · Afterlight",
    summary:
      "2025 Berlin feature produced by Tamsin Rowe. English-language, shot for EU and North American sales.",
    tags: ["feature", "afterlight", "berlin"],
    region: "Berlin",
    status: "Released",
    facts: [
      { label: "Studio", value: "Afterlight Media" },
      { label: "Year", value: "2025" },
      { label: "Producer", value: "Tamsin Rowe" },
      { label: "Sales", value: "Eastbound (English)" },
    ],
    credits: [
      { role: "Producer / lead", title: "Tamsin Rowe", year: "2025", kind: "performers", id: "tamsin-rowe" },
      { role: "Lead", title: "Omar Leclerc", year: "2025", kind: "performers", id: "omar-leclerc" },
      { role: "Lead", title: "Liora Chen", year: "2025", kind: "performers", id: "liora-chen" },
      { role: "Lead", title: "Felix Arden", year: "2025", kind: "performers", id: "felix-arden" },
    ],
    related: [
      { kind: "companies", id: "afterlight-media" },
      { kind: "companies", id: "eastbound" },
      { kind: "events", id: "venus-berlin-2026" },
    ],
    source: "index",
  },
  {
    id: "salt-and-copper",
    kind: "productions",
    name: "Salt & Copper",
    subtitle: "Feature · Pine & Vale",
    summary:
      "Maren Dahl directs in Vancouver, 2023. Amara Voss and Mateo Ruiz. Stills-led campaign.",
    tags: ["feature", "pine-vale", "vancouver"],
    region: "Vancouver",
    status: "Released",
    facts: [
      { label: "Studio", value: "Pine & Vale" },
      { label: "Year", value: "2023" },
      { label: "Director", value: "Maren Dahl" },
    ],
    credits: [
      { role: "Director / lead", title: "Maren Dahl", year: "2023", kind: "performers", id: "maren-dahl" },
      { role: "Lead", title: "Amara Voss", year: "2023", kind: "performers", id: "amara-voss" },
      { role: "Lead", title: "Mateo Ruiz", year: "2023", kind: "performers", id: "mateo-ruiz" },
      { role: "Supporting", title: "Sienna Park", year: "2023", kind: "performers", id: "sienna-park" },
    ],
    related: [{ kind: "companies", id: "pine-vale" }],
    source: "index",
  },
];
