/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as NightsRouteImport } from './routes/nights'
import { Route as OsRouteImport } from './routes/os'
import { Route as PassRouteImport } from './routes/pass'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as AcademyExamRouteImport } from './routes/academy.exam'
import { Route as AtelierIndexRouteImport } from './routes/atelier.index'
import { Route as AtelierSlugRouteImport } from './routes/atelier.$slug'
import { Route as AtlasIndexRouteImport } from './routes/atlas.index'
import { Route as AtlasKindRouteImport } from './routes/atlas.$kind'
import { Route as AtlasDossierRouteImport } from './routes/atlas.dossier'
import { Route as AtlasSavedRouteImport } from './routes/atlas.saved'
import { Route as AtlasSearchRouteImport } from './routes/atlas.search'
import { Route as AtlasSourcesRouteImport } from './routes/atlas.sources'
import { Route as LedgerIndexRouteImport } from './routes/ledger.index'
import { Route as LedgerActivityRouteImport } from './routes/ledger.activity'
import { Route as LedgerCollectionRouteImport } from './routes/ledger.collection'
import { Route as LedgerRewardsRouteImport } from './routes/ledger.rewards'
import { Route as LedgerWalletRouteImport } from './routes/ledger.wallet'
import { Route as LookbookIndexRouteImport } from './routes/lookbook.index'
import { Route as LookbookIdRouteImport } from './routes/lookbook.$id'
import { Route as OsIndexRouteImport } from './routes/os.index'
import { Route as OsHandleRouteImport } from './routes/os.$handle'
import { Route as OsDeskRouteImport } from './routes/os.desk'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as TalentIdRouteImport } from './routes/talent.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AtlasKindIndexRouteImport } from './routes/atlas.$kind.index'
import { Route as AtlasKindIdRouteImport } from './routes/atlas.$kind.$id'
import { Route as AtlasLiveQidRouteImport } from './routes/atlas.live.$qid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const NightsRoute = NightsRouteImport.update({
  id: '/nights',
  path: '/nights',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyExamRoute = AcademyExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AcademyRoute,
} as any)
const AtelierIndexRoute = AtelierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierSlugRoute = AtelierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AtelierRoute,
} as any)
const AtlasIndexRoute = AtlasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasKindRoute = AtlasKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasDossierRoute = AtlasDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasSavedRoute = AtlasSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasSearchRoute = AtlasSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AtlasRoute,
} as any)
const AtlasSourcesRoute = AtlasSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AtlasRoute,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerActivityRoute = LedgerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerCollectionRoute = LedgerCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerRewardsRoute = LedgerRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => LedgerRoute,
} as any)
const LedgerWalletRoute = LedgerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LedgerRoute,
} as any)
const LookbookIndexRoute = LookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LookbookRoute,
} as any)
const LookbookIdRoute = LookbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LookbookRoute,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRoute,
} as any)
const OsHandleRoute = OsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => OsRoute,
} as any)
const OsDeskRoute = OsDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => OsRoute,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRoute,
} as any)
const TalentIdRoute = TalentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TalentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasKindIndexRoute = AtlasKindIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtlasKindRoute,
} as any)
const AtlasKindIdRoute = AtlasKindIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AtlasKindRoute,
} as any)
const AtlasLiveQidRoute = AtlasLiveQidRouteImport.update({
  id: '/live/$qid',
  path: '/live/$qid',
  getParentRoute: () => AtlasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/apply': typeof ApplyRoute
  '/atelier': typeof AtelierRouteWithChildren
  '/atlas': typeof AtlasRouteWithChildren
  '/cart': typeof CartRoute
  '/desk': typeof DeskRoute
  '/join': typeof JoinRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRouteWithChildren
  '/nights': typeof NightsRoute
  '/os': typeof OsRouteWithChildren
  '/pass': typeof PassRoute
  '/services': typeof ServicesRoute
  '/talent': typeof TalentRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/exam': typeof AcademyExamRoute
  '/atelier/$slug': typeof AtelierSlugRoute
  '/atlas/$kind': typeof AtlasKindRouteWithChildren
  '/atlas/dossier': typeof AtlasDossierRoute
  '/atlas/saved': typeof AtlasSavedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/atlas/sources': typeof AtlasSourcesRoute
  '/ledger/activity': typeof LedgerActivityRoute
  '/ledger/collection': typeof LedgerCollectionRoute
  '/ledger/rewards': typeof LedgerRewardsRoute
  '/ledger/wallet': typeof LedgerWalletRoute
  '/lookbook/$id': typeof LookbookIdRoute
  '/os/$handle': typeof OsHandleRoute
  '/os/desk': typeof OsDeskRoute
  '/talent/$id': typeof TalentIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/atlas/': typeof AtlasIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/lookbook/': typeof LookbookIndexRoute
  '/os/': typeof OsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/atlas/$kind/$id': typeof AtlasKindIdRoute
  '/atlas/live/$qid': typeof AtlasLiveQidRoute
  '/atlas/$kind/': typeof AtlasKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/cart': typeof CartRoute
  '/desk': typeof DeskRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/nights': typeof NightsRoute
  '/pass': typeof PassRoute
  '/services': typeof ServicesRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/exam': typeof AcademyExamRoute
  '/atelier/$slug': typeof AtelierSlugRoute
  '/atlas/dossier': typeof AtlasDossierRoute
  '/atlas/saved': typeof AtlasSavedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/atlas/sources': typeof AtlasSourcesRoute
  '/ledger/activity': typeof LedgerActivityRoute
  '/ledger/collection': typeof LedgerCollectionRoute
  '/ledger/rewards': typeof LedgerRewardsRoute
  '/ledger/wallet': typeof LedgerWalletRoute
  '/lookbook/$id': typeof LookbookIdRoute
  '/os/$handle': typeof OsHandleRoute
  '/os/desk': typeof OsDeskRoute
  '/talent/$id': typeof TalentIdRoute
  '/academy': typeof AcademyIndexRoute
  '/atelier': typeof AtelierIndexRoute
  '/atlas': typeof AtlasIndexRoute
  '/ledger': typeof LedgerIndexRoute
  '/lookbook': typeof LookbookIndexRoute
  '/os': typeof OsIndexRoute
  '/talent': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/atlas/$kind/$id': typeof AtlasKindIdRoute
  '/atlas/live/$qid': typeof AtlasLiveQidRoute
  '/atlas/$kind': typeof AtlasKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/apply': typeof ApplyRoute
  '/atelier': typeof AtelierRouteWithChildren
  '/atlas': typeof AtlasRouteWithChildren
  '/cart': typeof CartRoute
  '/desk': typeof DeskRoute
  '/join': typeof JoinRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/legal': typeof LegalRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRouteWithChildren
  '/nights': typeof NightsRoute
  '/os': typeof OsRouteWithChildren
  '/pass': typeof PassRoute
  '/services': typeof ServicesRoute
  '/talent': typeof TalentRouteWithChildren
  '/academy/$slug': typeof AcademySlugRoute
  '/academy/exam': typeof AcademyExamRoute
  '/atelier/$slug': typeof AtelierSlugRoute
  '/atlas/$kind': typeof AtlasKindRouteWithChildren
  '/atlas/dossier': typeof AtlasDossierRoute
  '/atlas/saved': typeof AtlasSavedRoute
  '/atlas/search': typeof AtlasSearchRoute
  '/atlas/sources': typeof AtlasSourcesRoute
  '/ledger/activity': typeof LedgerActivityRoute
  '/ledger/collection': typeof LedgerCollectionRoute
  '/ledger/rewards': typeof LedgerRewardsRoute
  '/ledger/wallet': typeof LedgerWalletRoute
  '/lookbook/$id': typeof LookbookIdRoute
  '/os/$handle': typeof OsHandleRoute
  '/os/desk': typeof OsDeskRoute
  '/talent/$id': typeof TalentIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/atlas/': typeof AtlasIndexRoute
  '/ledger/': typeof LedgerIndexRoute
  '/lookbook/': typeof LookbookIndexRoute
  '/os/': typeof OsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/atlas/$kind/$id': typeof AtlasKindIdRoute
  '/atlas/live/$qid': typeof AtlasLiveQidRoute
  '/atlas/$kind/': typeof AtlasKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/apply'
    | '/atelier'
    | '/atlas'
    | '/cart'
    | '/desk'
    | '/join'
    | '/ledger'
    | '/legal'
    | '/live'
    | '/login'
    | '/lookbook'
    | '/nights'
    | '/os'
    | '/pass'
    | '/services'
    | '/talent'
    | '/academy/$slug'
    | '/academy/exam'
    | '/atelier/$slug'
    | '/atlas/$kind'
    | '/atlas/dossier'
    | '/atlas/saved'
    | '/atlas/search'
    | '/atlas/sources'
    | '/ledger/activity'
    | '/ledger/collection'
    | '/ledger/rewards'
    | '/ledger/wallet'
    | '/lookbook/$id'
    | '/os/$handle'
    | '/os/desk'
    | '/talent/$id'
    | '/academy/'
    | '/atelier/'
    | '/atlas/'
    | '/ledger/'
    | '/lookbook/'
    | '/os/'
    | '/talent/'
    | '/api/auth/$'
    | '/atlas/$kind/$id'
    | '/atlas/live/$qid'
    | '/atlas/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/cart'
    | '/desk'
    | '/join'
    | '/legal'
    | '/live'
    | '/login'
    | '/nights'
    | '/pass'
    | '/services'
    | '/academy/$slug'
    | '/academy/exam'
    | '/atelier/$slug'
    | '/atlas/dossier'
    | '/atlas/saved'
    | '/atlas/search'
    | '/atlas/sources'
    | '/ledger/activity'
    | '/ledger/collection'
    | '/ledger/rewards'
    | '/ledger/wallet'
    | '/lookbook/$id'
    | '/os/$handle'
    | '/os/desk'
    | '/talent/$id'
    | '/academy'
    | '/atelier'
    | '/atlas'
    | '/ledger'
    | '/lookbook'
    | '/os'
    | '/talent'
    | '/api/auth/$'
    | '/atlas/$kind/$id'
    | '/atlas/live/$qid'
    | '/atlas/$kind'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/apply'
    | '/atelier'
    | '/atlas'
    | '/cart'
    | '/desk'
    | '/join'
    | '/ledger'
    | '/legal'
    | '/live'
    | '/login'
    | '/lookbook'
    | '/nights'
    | '/os'
    | '/pass'
    | '/services'
    | '/talent'
    | '/academy/$slug'
    | '/academy/exam'
    | '/atelier/$slug'
    | '/atlas/$kind'
    | '/atlas/dossier'
    | '/atlas/saved'
    | '/atlas/search'
    | '/atlas/sources'
    | '/ledger/activity'
    | '/ledger/collection'
    | '/ledger/rewards'
    | '/ledger/wallet'
    | '/lookbook/$id'
    | '/os/$handle'
    | '/os/desk'
    | '/talent/$id'
    | '/academy/'
    | '/atelier/'
    | '/atlas/'
    | '/ledger/'
    | '/lookbook/'
    | '/os/'
    | '/talent/'
    | '/api/auth/$'
    | '/atlas/$kind/$id'
    | '/atlas/live/$qid'
    | '/atlas/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AtelierRoute: typeof AtelierRouteWithChildren
  AtlasRoute: typeof AtlasRouteWithChildren
  CartRoute: typeof CartRoute
  DeskRoute: typeof DeskRoute
  JoinRoute: typeof JoinRoute
  LedgerRoute: typeof LedgerRouteWithChildren
  LegalRoute: typeof LegalRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRouteWithChildren
  NightsRoute: typeof NightsRoute
  OsRoute: typeof OsRouteWithChildren
  PassRoute: typeof PassRoute
  ServicesRoute: typeof ServicesRoute
  TalentRoute: typeof TalentRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nights': {
      id: '/nights'
      path: '/nights'
      fullPath: '/nights'
      preLoaderRoute: typeof NightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/exam': {
      id: '/academy/exam'
      path: '/exam'
      fullPath: '/academy/exam'
      preLoaderRoute: typeof AcademyExamRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/atelier/': {
      id: '/atelier/'
      path: '/'
      fullPath: '/atelier/'
      preLoaderRoute: typeof AtelierIndexRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/$slug': {
      id: '/atelier/$slug'
      path: '/$slug'
      fullPath: '/atelier/$slug'
      preLoaderRoute: typeof AtelierSlugRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atlas/': {
      id: '/atlas/'
      path: '/'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AtlasIndexRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/$kind': {
      id: '/atlas/$kind'
      path: '/$kind'
      fullPath: '/atlas/$kind'
      preLoaderRoute: typeof AtlasKindRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/dossier': {
      id: '/atlas/dossier'
      path: '/dossier'
      fullPath: '/atlas/dossier'
      preLoaderRoute: typeof AtlasDossierRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/saved': {
      id: '/atlas/saved'
      path: '/saved'
      fullPath: '/atlas/saved'
      preLoaderRoute: typeof AtlasSavedRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/search': {
      id: '/atlas/search'
      path: '/search'
      fullPath: '/atlas/search'
      preLoaderRoute: typeof AtlasSearchRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/atlas/sources': {
      id: '/atlas/sources'
      path: '/sources'
      fullPath: '/atlas/sources'
      preLoaderRoute: typeof AtlasSourcesRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/activity': {
      id: '/ledger/activity'
      path: '/activity'
      fullPath: '/ledger/activity'
      preLoaderRoute: typeof LedgerActivityRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/collection': {
      id: '/ledger/collection'
      path: '/collection'
      fullPath: '/ledger/collection'
      preLoaderRoute: typeof LedgerCollectionRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/rewards': {
      id: '/ledger/rewards'
      path: '/rewards'
      fullPath: '/ledger/rewards'
      preLoaderRoute: typeof LedgerRewardsRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/ledger/wallet': {
      id: '/ledger/wallet'
      path: '/wallet'
      fullPath: '/ledger/wallet'
      preLoaderRoute: typeof LedgerWalletRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/lookbook/': {
      id: '/lookbook/'
      path: '/'
      fullPath: '/lookbook/'
      preLoaderRoute: typeof LookbookIndexRouteImport
      parentRoute: typeof LookbookRoute
    }
    '/lookbook/$id': {
      id: '/lookbook/$id'
      path: '/$id'
      fullPath: '/lookbook/$id'
      preLoaderRoute: typeof LookbookIdRouteImport
      parentRoute: typeof LookbookRoute
    }
    '/os/': {
      id: '/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/$handle': {
      id: '/os/$handle'
      path: '/$handle'
      fullPath: '/os/$handle'
      preLoaderRoute: typeof OsHandleRouteImport
      parentRoute: typeof OsRoute
    }
    '/os/desk': {
      id: '/os/desk'
      path: '/desk'
      fullPath: '/os/desk'
      preLoaderRoute: typeof OsDeskRouteImport
      parentRoute: typeof OsRoute
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRoute
    }
    '/talent/$id': {
      id: '/talent/$id'
      path: '/$id'
      fullPath: '/talent/$id'
      preLoaderRoute: typeof TalentIdRouteImport
      parentRoute: typeof TalentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$kind/': {
      id: '/atlas/$kind/'
      path: '/'
      fullPath: '/atlas/$kind/'
      preLoaderRoute: typeof AtlasKindIndexRouteImport
      parentRoute: typeof AtlasKindRoute
    }
    '/atlas/$kind/$id': {
      id: '/atlas/$kind/$id'
      path: '/$id'
      fullPath: '/atlas/$kind/$id'
      preLoaderRoute: typeof AtlasKindIdRouteImport
      parentRoute: typeof AtlasKindRoute
    }
    '/atlas/live/$qid': {
      id: '/atlas/live/$qid'
      path: '/live/$qid'
      fullPath: '/atlas/live/$qid'
      preLoaderRoute: typeof AtlasLiveQidRouteImport
      parentRoute: typeof AtlasRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyExamRoute: typeof AcademyExamRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyExamRoute: AcademyExamRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AtelierRouteChildren {
  AtelierSlugRoute: typeof AtelierSlugRoute
  AtelierIndexRoute: typeof AtelierIndexRoute
}

const AtelierRouteChildren: AtelierRouteChildren = {
  AtelierSlugRoute: AtelierSlugRoute,
  AtelierIndexRoute: AtelierIndexRoute,
}

const AtelierRouteWithChildren =
  AtelierRoute._addFileChildren(AtelierRouteChildren)

interface AtlasKindRouteChildren {
  AtlasKindIdRoute: typeof AtlasKindIdRoute
  AtlasKindIndexRoute: typeof AtlasKindIndexRoute
}

const AtlasKindRouteChildren: AtlasKindRouteChildren = {
  AtlasKindIdRoute: AtlasKindIdRoute,
  AtlasKindIndexRoute: AtlasKindIndexRoute,
}

const AtlasKindRouteWithChildren = AtlasKindRoute._addFileChildren(
  AtlasKindRouteChildren,
)

interface AtlasRouteChildren {
  AtlasKindRoute: typeof AtlasKindRouteWithChildren
  AtlasDossierRoute: typeof AtlasDossierRoute
  AtlasSavedRoute: typeof AtlasSavedRoute
  AtlasSearchRoute: typeof AtlasSearchRoute
  AtlasSourcesRoute: typeof AtlasSourcesRoute
  AtlasIndexRoute: typeof AtlasIndexRoute
  AtlasLiveQidRoute: typeof AtlasLiveQidRoute
}

const AtlasRouteChildren: AtlasRouteChildren = {
  AtlasKindRoute: AtlasKindRouteWithChildren,
  AtlasDossierRoute: AtlasDossierRoute,
  AtlasSavedRoute: AtlasSavedRoute,
  AtlasSearchRoute: AtlasSearchRoute,
  AtlasSourcesRoute: AtlasSourcesRoute,
  AtlasIndexRoute: AtlasIndexRoute,
  AtlasLiveQidRoute: AtlasLiveQidRoute,
}

const AtlasRouteWithChildren = AtlasRoute._addFileChildren(AtlasRouteChildren)

interface LedgerRouteChildren {
  LedgerActivityRoute: typeof LedgerActivityRoute
  LedgerCollectionRoute: typeof LedgerCollectionRoute
  LedgerRewardsRoute: typeof LedgerRewardsRoute
  LedgerWalletRoute: typeof LedgerWalletRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
}

const LedgerRouteChildren: LedgerRouteChildren = {
  LedgerActivityRoute: LedgerActivityRoute,
  LedgerCollectionRoute: LedgerCollectionRoute,
  LedgerRewardsRoute: LedgerRewardsRoute,
  LedgerWalletRoute: LedgerWalletRoute,
  LedgerIndexRoute: LedgerIndexRoute,
}

const LedgerRouteWithChildren =
  LedgerRoute._addFileChildren(LedgerRouteChildren)

interface LookbookRouteChildren {
  LookbookIdRoute: typeof LookbookIdRoute
  LookbookIndexRoute: typeof LookbookIndexRoute
}

const LookbookRouteChildren: LookbookRouteChildren = {
  LookbookIdRoute: LookbookIdRoute,
  LookbookIndexRoute: LookbookIndexRoute,
}

const LookbookRouteWithChildren = LookbookRoute._addFileChildren(
  LookbookRouteChildren,
)

interface OsRouteChildren {
  OsHandleRoute: typeof OsHandleRoute
  OsDeskRoute: typeof OsDeskRoute
  OsIndexRoute: typeof OsIndexRoute
}

const OsRouteChildren: OsRouteChildren = {
  OsHandleRoute: OsHandleRoute,
  OsDeskRoute: OsDeskRoute,
  OsIndexRoute: OsIndexRoute,
}

const OsRouteWithChildren = OsRoute._addFileChildren(OsRouteChildren)

interface TalentRouteChildren {
  TalentIdRoute: typeof TalentIdRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentIdRoute: TalentIdRoute,
  TalentIndexRoute: TalentIndexRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AtelierRoute: AtelierRouteWithChildren,
  AtlasRoute: AtlasRouteWithChildren,
  CartRoute: CartRoute,
  DeskRoute: DeskRoute,
  JoinRoute: JoinRoute,
  LedgerRoute: LedgerRouteWithChildren,
  LegalRoute: LegalRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRouteWithChildren,
  NightsRoute: NightsRoute,
  OsRoute: OsRouteWithChildren,
  PassRoute: PassRoute,
  ServicesRoute: ServicesRoute,
  TalentRoute: TalentRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
